### ISSUE TITLE
Exception when scanning library

### ISSUE THREAD

**Issue by joelaw9** [Kareadita/Kavita#3434] opened 2024-12-02 14:34 UTC
### What happened?

My library fails to scan, throwing exceptions at the 'Library Manga Step 2: Process and Update Database' step.  All new chapters are ignored. 

### What did you expect?

The scan to complete and new chapters to get added.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.4.2 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-12-02 04:00:31.745 -06:00  85] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library Manga Step 2: Process and Update Database
[Kavita] [2024-12-02 04:00:31.747 -06:00  85] [Information] API.Services.Tasks.ScannerService [ScannerService] Attempting to pre-save all Genres
[Kavita] [2024-12-02 04:00:31.754 -06:00  85] [Information] API.Services.Tasks.ScannerService [ScannerService] Attempting to pre-save all Tags
[Kavita] [2024-12-02 04:00:31.756 -06:00  85] [Information] API.Services.Tasks.ScannerService [ScannerService] Found 30 Series that need processing in 20435 ms
[Kavita] [2024-12-02 04:00:31.756 -06:00  85] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on Baby Prisoner of the Winter Castle [Official], Forced: false
[Kavita] [2024-12-02 04:00:31.776 -06:00  85] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Processing series Baby Prisoner of the Winter Castle [Official] with 47 files
[Kavita] [2024-12-02 04:00:31.777 -06:00  85] [Error] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] There was an exception updating series for Baby Prisoner of the Winter Castle [Official]
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.get_NumberFormat()
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateChapters(Series series, Volume volume, IList`1 parsedInfos, Boolean forceUpdate) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ProcessSeries.c>
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateVolumes(Series series, IList`1 parsedInfos, Boolean forceUpdate) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ProcessSeries.cs:line 624
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Int32 totalToProcess, Boolean forceUpdate) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\Pr>
[Kavita] [2024-12-02 04:00:31.779 -06:00  85] [Debug] API.Services.Tasks.ScannerService [TIME] Kavita took 22 ms to process Baby Prisoner of the Winter Castle [Official]
[Kavita] [2024-12-02 04:00:31.779 -06:00  85] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on Yuusha Densetsu no Uragawa de Ore wa Eiyuu Densetsu o Tsukurimasu: Oudou Goroshi no E>
[Kavita] [2024-12-02 04:00:31.786 -06:00  85] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Processing series Yuusha Densetsu no Uragawa de Ore wa Eiyuu Densetsu o Tsukurimasu: Oudou Goroshi no Eiyuutan~ >
[Kavita] [2024-12-02 04:00:31.787 -06:00  85] [Error] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] There was an exception updating series for Yuusha Densetsu no Uragawa de Ore wa Eiyuu Densetsu o Tsukurimasu: Oudou Go>
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.get_NumberFormat()
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateChapters(Series series, Volume volume, IList`1 parsedInfos, Boolean forceUpdate) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ProcessSeries.c>
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateVolumes(Series series, IList`1 parsedInfos, Boolean forceUpdate) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ProcessSeries.cs:line 624
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Int32 totalToProcess, Boolean forceUpdate) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\Pr>
[Kavita] [2024-12-02 04:00:31.787 -06:00  85] [Debug] API.Services.Tasks.ScannerService [TIME] Kavita took 8 ms to process Yuusha Densetsu no Uragawa de Ore wa Eiyuu Densetsu o Tsukurimasu: Oudou Goroshi no Eiyuutan~
[Kavita] [2024-12-02 04:00:31.787 -06:00  85] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on Behold the True Villainess, Forced: false
[Kavita] [2024-12-02 04:00:31.811 -06:00  85] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Processing series Behold the True Villainess with 135 files
[Kavita] [2024-12-02 04:00:31.811 -06:00  85] [Error] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] There was an exception updating series for Behold the True Villainess
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.get_NumberFormat()
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateChapters(Series series, Volume volume, IList`1 parsedInfos, Boolean forceUpdate) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ProcessSeries.c>
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateVolumes(Series series, IList`1 parsedInfos, Boolean forceUpdate) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ProcessSeries.cs:line 624
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Int32 totalToProcess, Boolean forceUpdate) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\Pr>
[Kavita] [2024-12-02 04:00:31.811 -06:00  85] [Debug] API.Services.Tasks.ScannerService [TIME] Kavita took 24 ms to process Behold the True Villainess
```

### Additional Notes

Running on an LXC on Proxmox, the manga files are hosted on a network share. Everything works if I roll back to 8.3.0

**Comment by scare376** [comment] 2024-12-02 15:12
This is a duplicate of #3413. Please follow that issue and add your comments there

**Closed as completed by scare376** 2024-12-02 15:12 UTC
Labels: needs-triage
