### ISSUE TITLE
Comic volume marker grouping with issue

### ISSUE THREAD

**Issue by therobbiedavis** [Kareadita/Kavita#869] opened 2021-12-22 14:46 UTC
Getting a bug where a comic with a volume marker is getting parsed with an issue.

Running version 0.4.9.23 on docker.

Volume file name:
Adventure Time TPB (2012)/Adventure Time v01 (2012).cbz

Issue file name:
Adventure Time (2012)/Adventure Time #001 (2012).cbr

![image](https://user-images.githubusercontent.com/7907265/147110181-2cb75743-d3fa-46dd-88f1-58c9dd6b8a66.png)

**Comment by majora2007** [comment] 2022-01-08 19:30
I can't reproduce this myself

**Comment by Shadowghost** [comment] 2023-03-13 21:55
I can reproduce this on the current nightly build with the exact same layout as the original issue.
What's the reason this is `wontfix`?

**Comment by majora2007** [comment] 2023-03-13 23:11
Because I can't reproduce as stated from Jan. Can you provide two files (with non copyrighted images) and the needed metadata for me to reproduce?

**Comment by Shadowghost** [comment] 2023-03-14 20:26
Seems like my I was a bit fast on claiming it's the same bug. But it still seems to be related:
Library Layout:
```
Test Publisher
|-- Free Form
     |--- Free Form #001.cbz
     ...
|-- Free Form TPB
     |--- Free Form TPB v1.cbz
     ...
```
Will be merged into a single series named `Free Form` with volumes and issue from both folders, this is also the case if you remove the `TPB` from the filename of files of the second folder:
![grafik](https://user-images.githubusercontent.com/3741446/225126704-1ddbc003-36cb-4891-9699-d0e47e16edea.png)

If you rename the volumes to issues (`Free Form TPB #001.cbz`), they are merged into a single series with duplicate issues (even though they include `TPB` in their file name which should mark them as specials according to the docs):
![grafik](https://user-images.githubusercontent.com/3741446/225126899-0ebb3037-5bc1-4596-bd85-822a92d89462.png)

Content of the library: https://drive.google.com/file/d/1fU3meevongQ1fMAEYQJAzmJUD0bEYGCl/view?usp=share_link
Since the bugs are not really the same, I can put it into it's own issue if you prefer.

**Comment by majora2007** [comment] 2023-03-14 21:40
@Shadowghost Let's create another issue and I'll reply on that.

**Closed** 2023-03-14 21:41 UTC
Labels: enhancement, wontfix, Parser
