### ISSUE TITLE
Immersive Mode doesn't work if Tap pagination is disabled

### ISSUE THREAD

**Issue by tsmox-alt** [Kareadita/Kavita#2505] opened 2023-12-23 13:52 UTC
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Running 7.11.2 , when I read a book and enable Immersive mode and disable pagination, I cannot click to hide or show the UI, instead the only thing I can do is highlight a word to bookmark it
if pagination is enabled, it works as normal

**To Reproduce**
1. Open any book
2. Click on the hamburger menu
3. Enable Immersive mode
4. Disable pagination
5. Click in the reader
6. Bug

**Expected behavior**
The UI should go away when clicking with Immersive mode enabled

**Smartphone (please complete the following information):**
 - Device: S22/Samsung Tab 7 Lite
 - OS: One Ui 6/One ui 5.1.1
 - Browser: Every browser that I tried
 - Version 7.11.2

**Additional context**
I updated from 7.5.0 to 7.11.2 not long ago

**Comment by majora2007** [comment] 2024-01-02 13:17
Duplicate of #1997

**Closed as completed by majora2007** 2024-01-02 13:17 UTC
Labels: needs-triage
