### ISSUE TITLE
Bug with cross-reference Links in EPUBs causing incorrect page and text display

### ISSUE THREAD

**Issue by zeedif** [Kareadita/Kavita#2081] opened 2023-06-18 18:13 UTC
**Describe the bug**
When using cross-reference links in my EPUB section notes, which subsequently refer back to a superscript, an issue arises causing the e-reader to incorrectly display two pages and cut off the text. This is intended to help the user return to their original reading point, but instead, it disrupts the reading experience.

**To Reproduce**
1. Go to any EPUB file with cross-reference links in the text.
2. Click on the cross-reference link that leads to notes section.
3. After viewing the note, click on the note to return to the original reading point.
4. See error - the e-reader displays two pages and cuts off the text.

**Expected behavior**
I expect the e-reader to correctly return to the same reading point from where the cross-reference link was clicked, without displaying two pages or cutting off the text.

**Screenshots**
I add a video to demonstrate the problem.

https://github.com/Kareadita/Kavita/assets/60901341/41109df2-bd7b-4c89-a27c-4471ccbaed20

**Desktop**
 - Browser: Microsoft Edge
 - Version: Kavita 0.7.3.2

**Comment by majora2007** [comment] 2023-06-18 21:24
Since you create your own, can you attach a sample book for me?

**Comment by zeedif** [comment] 2023-06-19 14:17
This is a folder with some of my own epubs:
https://1drv.ms/f/s!AtXUisPt_TL8j5NF3h9GHN-XAGoAEA

**Comment by majora2007** [comment] 2023-06-29 16:58
I wasn't able to reproduce the linking causing skew on double column layout, however, I did find that <a><sup>text</sup></a> wouldn't trigger inner-book navigation and did clean that up.

**Comment by majora2007** [comment] 2023-06-29 16:58
Perhaps you can tell me the exact book you're using and exact page number so I can try on that. I just used another one I found in your link.

**Comment by majora2007** [comment] 2023-07-10 16:51
This will be released in v0.7.4.

**Closed by majora2007** 2023-07-10 16:51 UTC
Labels: needs-triage
