### ISSUE TITLE
Error : 400 [X] - Could not Save Progress.

### ISSUE THREAD

**Issue by Draknars** [Kareadita/Kavita#878] opened 2022-01-02 04:36 UTC
**Describe the bug**

I get the following error : 400 [X (being a number)] - Could not Save Progress. when moving to the next chapter.
I believe that I narrowed down that the most common occurence is when I use the scrolling read mode, it's much less frenquent with the normal reading mode.

Other symptoms of caused or related to this issue : 

- Sometime even though the page reloads, I am back in the same chapter, either the first page or the last one.
- Sometime I progress to the next chapter. However it as if it put me back on last page of the previous chapter (so usualy the last page), meaning I have to use the scroll to manually get back to the first page.
- Sometime, even though I get the error, it progress to the next chapter without issue. 

**To Reproduce**
1.  Open any Manga/Webtoon
2.  Switch to scrolling read mode
3.  Scroll down to the end
4.  if unable to ''scroll down to next chapter'', manually click on the next chapter icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/40360399/147866220-a29380e4-3a7e-4709-9d4e-0c9da4de62aa.png)

**Server / Host (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS running Kavita in Docker
 - Version 0.4.9.1
 - Docker Image : kizaing/kavita:latest

**Smartphone (please complete the following information):**
 - Device: iPhone XR & iPad Pro Gen3
 - Browser : Safari / Edge

**Troubleshooting**
- Host/Server : Recreated the container, recreated the libraries 
- Clients : Cleared cache - Changed browsers (Tried Edge and Safari) 
- Content format: Manga / Webtoon in .CBZ format
- Seems that the error is much less frequent in normal scrolling mode

**Additional info**
Not 100% sure it's related, but I got this excerpt from my logs about when the error occur (Happy to provide more log if needed) : 
2022-01-02T03:29:57.042613715Z       Executing PhysicalFileResult, sending file '/kavita/config/cache/12249/10.jpg' with download name '10.jpg' ...
2022-01-02T03:29:57.043587176Z fail: API.Interfaces.Services.ReaderService[0]
2022-01-02T03:29:57.043600454Z       Could not save progress
2022-01-02T03:29:57.043607907Z       Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.

**Comment by majora2007** [comment] 2022-01-02 18:35
I have def seen this before in the webtoon reading mode from what I think is saving too fast when scrolling quickly, but testing and reproducing has proved challenging for me. I'll leave this open and slot it for a further release.

**Comment by Draknars** [comment] 2022-01-03 03:04
> I have def seen this before in the webtoon reading mode from what I think is saving too fast when scrolling quickly, but testing and reproducing has proved challenging for me. I'll leave this open and slot it for a further release.

Thanks for the prompt answer, I will try additional troubleshooting if I can help isolate the issue and facilitate reproduction. Let me know if I can do anything (screen recording, logs, etc.) More than happy to help support your fantastic project, it is what made me start reading Manga in the first place!

**Comment by majora2007** [comment] 2022-01-03 14:16
Thanks, I'm glad to hear that.

**Comment by majora2007** [comment] 2022-01-28 14:59
Are you still having this issue? I did a bit of optimizations in v0.5. just curious if I need to revisit next release.

**Comment by Draknars** [comment] 2022-01-30 18:56
> Are you still having this issue? I did a bit of optimizations in v0.5. just curious if I need to revisit next release.

Unfortunately, the issue is still present, if anything I have more issues with the reader mode overall with the latest update. (Scaling issue for example, but that's another story for another time...) 

Were you able to reproduce the issue?

- From my experience it's really tied with this specific Scrolling Reading mode when using the standard page mode I don't experience this issue. 
- Another thing I tested is to switch the page mode before going to the next chapter, and so far this issue does not occur when doing so, although it's so clunky that is easier to not bother with it, it an interesting observation.
- You mentioned scrolling too quickly, so one thing I also tried is when arriving to the last page, to wait (usually 10-30 seconds) before proceeding to the next chapter. Unfortunately, it had no effect on the error.
- I looked at the nomenclature of the jpg files in the .CBZ files to see if it could have an impact. However most them are either something like ( 01, 02, 03, 04, etc. ) or a prefix followed by the numbering ( sometime in the chapter name followed by the page number, for example) so nothing concluant here. 


I added below a longer excerpt from my docker logs as well. 

It's a wild guess, but could it be possible that since scrolling preload images in a continuous format, it's trying to preload something does not exist yet (either not loaded or set a proper path) causing the issue?





```
2022-01-30T16:13:49.757648498Z info: Microsoft.AspNetCore.Mvc.Infrastructure.PhysicalFileResultExecutor[1]

2022-01-30T16:13:49.757663914Z       Executing PhysicalFileResult, sending file '/kavita/config/cache/30677/01.jpg' with download name '01.jpg' ...

2022-01-30T16:13:49.757751872Z fail: API.Services.ReaderService[0]

2022-01-30T16:13:49.757763661Z       Could not save progress

2022-01-30T16:13:49.757770095Z       Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.

2022-01-30T16:13:49.757777137Z          at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)

2022-01-30T16:13:49.757783266Z          at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)

2022-01-30T16:13:49.757789464Z          at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)

2022-01-30T16:13:49.757795429Z          at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)

2022-01-30T16:13:49.757801397Z          at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)

2022-01-30T16:13:49.757807499Z          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)

2022-01-30T16:13:49.757813729Z          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)

2022-01-30T16:13:49.757819855Z          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)

2022-01-30T16:13:49.757826643Z          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)

2022-01-30T16:13:49.757832793Z          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

2022-01-30T16:13:49.757847761Z          at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

2022-01-30T16:13:49.757854780Z          at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

2022-01-30T16:13:49.757860963Z          at API.Data.UnitOfWork.CommitAsync() in /home/runner/work/Kavita/Kavita/API/Data/UnitOfWork.cs:line 75

2022-01-30T16:13:49.757866907Z          at API.Services.ReaderService.SaveReadingProgress(ProgressDto progressDto, Int32 userId) in /home/runner/work/Kavita/Kavita/API/Services/ReaderService.cs:line 191

2022-01-30T16:13:49.758682480Z info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]

2022-01-30T16:13:49.758699446Z       Executing BadRequestObjectResult, writing value of type 'System.String'.

2022-01-30T16:13:49.758807354Z info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]

2022-01-30T16:13:49.758820716Z       Executed action API.Controllers.ReaderController.BookmarkProgress (API) in 366.0912ms

2022-01-30T16:13:49.758826185Z info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]

2022-01-30T16:13:49.758830698Z       Executed endpoint 'API.Controllers.ReaderController.BookmarkProgress (API)'

2022-01-30T16:13:49.758834775Z info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

2022-01-30T16:13:49.758839045Z       Request finished HTTP/1.1 POST http://10.0.4.3:5000/api/reader/progress application/json 83 - 400 - text/plain;+charset=utf-8 366.6163ms

2022-01-30T16:13:49.765105667Z info: Microsoft.AspNetCore.Hosting.Diagnostics[1]

2022-01-30T16:13:49.765120511Z       Request starting HTTP/1.1 GET http://10.0.4.3:5000/api/reader/image?chapterId=30677&page=1 - -

2022-01-30T16:13:49.765176351Z info: Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware[24]

2022-01-30T16:13:49.765190375Z       No cached response available for this request.
```

**Comment by majora2007** [comment] 2022-01-30 19:02
Thanks for getting back to me, can you confirm you're on v0.5.0+?

**Comment by Draknars** [comment] 2022-01-30 19:06
> Thanks for getting back to me, can you confirm you're on v0.5.0+?
Yup, as soon it was released 
![image](https://user-images.githubusercontent.com/40360399/151713681-9f6a3afb-4e23-4964-8f37-db21679dd9f4.png)

**Comment by majora2007** [comment] 2022-01-30 19:08
Okay, awesome. I still have this slated, but I will do one more thing. I'm pretty sure the error you're seeing is basically nothing. A few too many requests hit the backend and the backend says, nothing's changed but in an error, so it looks like an error. I'll look at putting some suppression in for this case.

**Comment by Draknars** [comment] 2022-01-30 19:11
> Okay, awesome. I still have this slated, but I will do one more thing. I'm pretty sure the error you're seeing is basically nothing. A few too many requests hit the backend and the backend says, nothing's changed but in an error, so it looks like an error. I'll look at putting some suppression in for this case.

Got it, unfortunately it was my only lead on the matter, let me know when you have made some progress or if I can help"

I'll be sure to test and report on your next update !

**Comment by majora2007** [comment] 2022-02-11 19:02
No rush, just poking in since v0.5.1 just went out. Let me know on this. Hopefully it's been sorted.

**Comment by Draknars** [comment] 2022-02-12 02:32
Unfortunately, the update 0.5.1 is not working out for me, the "One time migration" account failed and now I can no longer access Kavitaat all. I was planning thinkering with it, and maybe rollback and report it if I can't fix it

**Comment by majora2007** [comment] 2022-02-12 02:48
You can rollback, but the one time migration should have put a link in your logs. As long as you use that link on your instance it will work.

**Comment by Draknars** [comment] 2022-02-12 03:22
Thanks for the tip for the log.

The only Link I was able to find in the logs is this :

`2022-02-11T18:18:18.1216989-05:00	INFO	[API.Controllers.AccountController]	[0]	[Email Migration]: Email Link for [USER]: http://[**SERVER_IP**]:5000/registration/confirm-migration-email?token=[**STRING**]

but when trying to access the link, I get this : 

![image](https://user-images.githubusercontent.com/40360399/153694552-0f5ccc6f-0f1f-4af5-a2a7-a45b74f5f231.png)

When I first login, I entered my email address for the migration, but clicking on the "Next" button was not doing anything, I waited for a while, check my junk just in case, but nothing. Upon refreshing I tried to log back in but now I am only getting this : 

![image](https://user-images.githubusercontent.com/40360399/153694636-08045db1-4a3f-4550-b39a-a8992185227b.png)

Unfortunately, It does not appear that I have the ability to resend a token or enter a different email address

**Comment by Draknars** [comment] 2022-02-16 21:09
@majora2007 Thanks your hotfix I was able to access Kavita again, fantastic! 

As for the bug, I can confirm I still experience it. I don't have tangible evidence, but it does appear to be less frequent. However, I now experience a new issue where sometime when I load a new chapter, all the images are black, I have to go to the navigation and click on the page scrolling bar in order to "refresh" the images and make them appear.

**Comment by majora2007** [comment] 2022-02-16 21:13
Create another issue for your black issue and make sure to put your browser info and the way your accessing (network speed). I've never seen that issue before.

**Comment by Draknars** [comment] 2022-04-12 19:29
@majora2007 Following up on this issue, I just want to say that with version 5.2 I believe the issue has been fixed, it happened once or twice, but overall it drastically improved with the lasted version!

**Comment by majora2007** [comment] 2022-04-12 19:35
Music to my ear. We can close it. I haven't been able to reproduce for a while now. If it ever crops up consistently, please just reopen and ping me on it.

**Closed by majora2007** 2022-04-12 19:35 UTC
Labels: bug, UI

**Comment by UlyssesZh** [comment] 2023-11-05 18:18
I am seeing this in 0.7.x. It happens when I jump to a far position in a PDF.

**Comment by majora2007** [comment] 2023-11-05 18:25
> eing this in 0.7.x. It happens when I jump to a far position in a PDF.

Please create a new issue for me and we can debug from there.
