### ISSUE TITLE
Library folders on Raspberry Pi 3 (armhf)

### ISSUE THREAD

**Issue by LelieL91** [Kareadita/Kavita#557] opened 2021-09-06 16:45 UTC
**Describe the bug**
When I try to add a folder to a new library, it shows me a bunch of system directory but no home dir. I run Kavita v0.4.5 armhf version without docker as pi user, so it shouldn't be a permission issue.

**To Reproduce**
1. Go to 'Server settings'
2. Click on 'Libraries > Add Library'
3. Scroll down to 'Folders' and click '+'

**Expected behavior**
Seeing /home/pi directory and sub directory

**Screenshots**
![immagine](https://user-images.githubusercontent.com/48968075/132245865-5f6ccc5d-06cb-4f8e-8f9b-4b77452c5521.png)

**Desktop (please complete the following information):** (CLIENT)
 - OS: Windows 10 21H1 x64
 - Browser: Mozilla Firefox
 - Version: v91.0.2 x64

**Desktop (please complete the following information):** (SERVER)
 - OS: Raspberry OS Buster armhf

**Comment by ChristofferGreen** [comment] 2021-09-06 18:31
It's the same for me, one workaround is to click on '/', then it shows /home/. Would be nicer if it did not show all the system dirs though.

**Comment by majora2007** [comment] 2021-09-06 18:34
What error are you seeing? 

/ is the mount point of the docker. It would be like C:/ for my Windows machine.

**Comment by LelieL91** [comment] 2021-09-06 18:43
> 
> 
> It's the same for me, one workaround is to click on '/', then it shows /home/. Would be nicer if it did not show all the system dirs though.

Oh, I didn't try that. What a noob ahahah
By the way it's kind annoying that system folders list. If you run the application using an user, those folders are not even accessible.


> 
> 
> What error are you seeing?
> 
> / is the mount point of the docker. It would be like C:/ for my Windows machine.

The error is that there is a folder list made by private system folders and the /home/ folder that is the Default user folder is not there. You need to find the path by navigating the root "/". Since this is my first installation and approach to Kavita, it's kind confusing.
This list is also useless since the user that run Kavita doesn't have any write or access permission on those. 
 BTW, thank you all for your replies

**Comment by ChristofferGreen** [comment] 2021-09-06 18:56
It took me a maybe an hour or two to figure out as well when I first ran across it :)

It may be that we either need better documentation or a linux/unix specific fix (which would be ugly for the code and may not be what we want)

**Comment by majora2007** [comment] 2021-09-06 18:56
Yeah, I totally understand where you are coming from. I can't change the implementation in this case, due to how windows works and the APIs I'm using. What I will do is put a link to our wiki which has information, like clicking on / for linux-based users. 

The issue is here and will be shipped in the next release
https://github.com/Kareadita/Kavita/issues/559

I'm going to close this issue. (You can comment on top of it, if we need to open it back up).

**Closed by majora2007** 2021-09-06 18:56 UTC
Labels: needs-triage
