### ISSUE TITLE
Series Images are Lost but Still Appear in Metadata Selection as Active

### ISSUE THREAD

**Issue by armouredking** [Kareadita/Kavita#1249] opened 2022-05-10 14:51 UTC
I'm not sure if the cover thing is related to #1244 or not, but it seems to have come back as well despite having no specials. These were working last night (ie the volume covers showed the uploaded images), and per the metadata system they are still there, but the images are now wrong. When I got rid of the specials I also removed the files, scanned, and put them back after renaming them sans specials (basically a Plex dance) for a final scan to try and clear any caches that might have been created.

![image](https://user-images.githubusercontent.com/16038428/167307398-8c776ed2-7344-4f96-92ba-aef0fc5e9a0f.png)
![image](https://user-images.githubusercontent.com/16038428/167307415-faa7cfc0-393e-4448-8947-a48c162eb399.png)

Logging in from another browser (ie using Firefox instead so there is no browser cache) does not fix them either.

_Originally posted by @armouredking in https://github.com/Kareadita/Kavita/issues/1244#issuecomment-1120454821_

**Comment by majora2007** [comment] 2022-05-10 15:00
So if you were to rewrite this in the way issue template asks you, what are the steps I can take to reproduce this? 

1. Open a series
2. Add a custom cover to Volume 1
3. etc
Expected:
Cover image stays
Actual:
etc

Can you fill this information out for me, so i can test it on my machine?

**Comment by armouredking** [comment] 2022-05-11 05:02
FYI: There is no template provided when creating an issue from an issue. Can try and drop this in from another new issue:

**To Reproduce**
Steps to reproduce the behavior:
1. Upload a new series
2. Scan and wait for Kavita to propagate data
3. Click on a volume in the newly added series
4. Navigate: ... --> Details --> Cover
5. Upload a cover image and hit save
6. Cover image will show up initially, and cover image from ... --> Details --> Cover should be uploaded image next to a black Reset selection
7. Wait for reoccurring tasks to occur
8. See first comment for results. Metadata editor will still show cover image as being active, but it will not be that way in Kavita itself.

I have seen this happen now regardless of specials being present in the series, and it happens to the entire library, so it is likely not related to #1244. Followup example with a different series:

![image](https://user-images.githubusercontent.com/16038428/167772410-bec43406-d98f-4b9e-93d8-68c43898da6a.png)
![image](https://user-images.githubusercontent.com/16038428/167772487-b1aa7c0e-217b-4354-894d-c75e09b2c038.png)

**Expected behavior**
Do not lose cover images added with metadata editor. If cover images are lost or reset through some setting / action / etc, this should be reflected by metadata editor in Kavita. Might be necessary to have a setup where we choose source priority of cover images?

**Desktop/Environment:**
Brave V1.38.111 Chromium 101.0.4951.54
Windows 11 Client, Docker CE Server using Latest tag image 0.5.2

**Bonus Notice:**

![image](https://user-images.githubusercontent.com/16038428/167772142-1c60f9b1-e0a4-4931-8ead-0c0caa278388.png)
Metadata is spelled incorrectly in the tasks tooltip.

**Comment by majora2007** [comment] 2022-05-17 12:42
I can't reproduce this issue. Perhaps instead you are experiencing a caching issue where the original issue is cached and being shown? 

Can you validate your version is 0.5.2 or 0.5.2.5? There were some hotfixes that occurred, but this is a tested scenario for release and no other user has complained, so maybe something else is happening on your system that we need to investigate.

**Comment by armouredking** [comment] 2022-05-17 15:49
Yes, I am using Docker, so environment is static.

![image](https://user-images.githubusercontent.com/16038428/168853087-445b3946-8c82-4524-b069-62e6e0435cdc.png)

Logging in via a different browser or using InPrivate modes does not show the right images either, so unlikely to be cache related unless the Docker instance is the caching issue.

**Comment by majora2007** [comment] 2022-05-17 16:03
Can you please show the version in Admin Settings -> System tab?

**Comment by armouredking** [comment] 2022-05-17 16:09
![image](https://user-images.githubusercontent.com/16038428/168858183-20529597-f2e7-41cd-a26a-45ff1c76708a.png)

**Comment by coscosname** [comment] 2022-05-24 18:50
I have the same problem with the volume covers. (Kavita Version 0.5.3.0)

From what I've noticed the problem is due to the fact that the volume cover is set for some (random?) chapter of a volume and not for the volume itself.

When fetching the volume covers in the volume list, they are fetched as `volume-cover`.
`Request starting HTTP/1.1 GET http://mysite.abc/api/image/volume-cover?volumeId=166&offset=0 - -`.
 which gives us the volume cover.

![image](https://user-images.githubusercontent.com/89737988/170107748-cc1baefe-deb9-4318-b382-371c1aaf6701.png)


And when editing a volume and the cover shown there comes from some chapter of the given volume (random?) `chapter-cover`.
`Request starting HTTP/1.1 GET http://mysite.abc/api/image/chapter-cover?chapterId=531 - -`

![image](https://user-images.githubusercontent.com/89737988/170108186-c5af2f54-e17d-47e7-b8df-c8e2df4250eb.png)

Chapter with "volume cover"
![image](https://user-images.githubusercontent.com/89737988/170109485-bd96e451-5ce9-42a8-bf4b-cd18ed20e035.png)

When we check the chapter ID, we find that it is the same as the "cover" in the volume metadata edition (chapterId=531).
![image](https://user-images.githubusercontent.com/89737988/170109771-dc631a8d-1914-4265-b39f-945262617f07.png)


The implication is that when adding a volume cover, it is assigned as the cover of some (random?) chapter from that volume and not to the volume itself. So when displaying volumes we get the "original" covers because they are taken from `volume-cover` and when editing the volume metadata we get the preset cover because there it is taken from some chapter `chapter-cover`

It follows that the problem is:
- assigning the cover to the volume
- getting the cover in the metadata edition

**Comment by majora2007** [comment] 2022-05-24 19:04
Please create a different issue for the cover issue rather than adding onto this.

**Comment by majora2007** [comment] 2023-03-02 03:21
Going to close this issue. If it's still present, please comment and I'll reopen to investigate.

**Closed by majora2007** 2023-03-02 03:21 UTC
Labels: can't reproduce
