### ISSUE TITLE
Epubs with Series values that do not include a whole number not recognised properly

### ISSUE THREAD

**Issue by hmesser1** [Kareadita/Kavita#727] opened 2021-11-05 14:17 UTC
Epubs imported fail to be processed properly if included in a series and the value is not a whole number. So, an epub is 12.5 in a series. This sometimes occurs with short stories added into a series.

**To Reproduce**
Add metadata to an epub that includes a value plus half, eg 12.5 and import
Add metadata to an epub to a book that includes a series value of 12 and import.
Both are recognised as volume 12. 

**Expected behavior**
epubs should be recognised as separate books

**Comment by majora2007** [comment] 2021-11-05 14:46
Hello hmesser, 

Can you give me an example epub metadata file (opf) or the exact xml and how we are currently grouping vs how you expect? 

You can also join discord and PM me a book, so I can test with that.

**Comment by dmryce** [comment] 2021-11-08 13:48
> Hello hmesser,
> 
> Can you give me an example epub metadata file (opf) or the exact xml and how we are currently grouping vs how you expect?
> 
> You can also join discord and PM me a book, so I can test with that.

Not the OP, but I believe I experienced this yesterday. If you have a book with a series value of 2 in a series for example, and attempt to add a book with a series value of 2.5 within that same series, it doesn't add the book with the 2.5 value. I'll go back and test to see if it's actually replacing the original volume 2 instead of seeing it as a new book in the series. I hadn't thought of that when I was trying to figure out the issue. I can send a book on Discord and/or the opf file if that helps.

**Comment by majora2007** [comment] 2021-11-08 15:35
Okay this helps me quickly reproduce it myself. I'll take a look into it this week.

**Comment by dmryce** [comment] 2021-11-08 16:10
> 
> 
> > Hello hmesser,
> > Can you give me an example epub metadata file (opf) or the exact xml and how we are currently grouping vs how you expect?
> > You can also join discord and PM me a book, so I can test with that.
> 
> Not the OP, but I believe I experienced this yesterday. If you have a book with a series value of 2 in a series for example, and attempt to add a book with a series value of 2.5 within that same series, it doesn't add the book with the 2.5 value. I'll go back and test to see if it's actually replacing the original volume 2 instead of seeing it as a new book in the series. I hadn't thought of that when I was trying to figure out the issue. I can send a book on Discord and/or the opf file if that helps.

I can verify that it's actually replacing the original book that has a series value of 2 with the book that has a series value of 2.5. So it seems as of right now, Kavita can't identify books labeled in this manner as two separate items.

**Comment by majora2007** [comment] 2021-11-08 16:35
Let me just double make sure. When you say series value you mean:

Harry Potter 2 and Harry Potter 2.5?

Or do you mean series_index for grouping books into a series?

**Comment by dmryce** [comment] 2021-11-08 16:51
> 
> 
> Let me just double make sure. When you say series value you mean:
> 
> Harry Potter 2 and Harry Potter 2.5?
> 
> Or do you mean series_index for grouping books into a series?

Yes. Harry Potter 2 and Harry Potter 2.5 is an example of what I am talking about. 

Actually it's not replacing the file. The one that displays correctly seems to depend on which one is there first. It seems to be trying to combine them. See the link below.

[Kavita Info Screen For Book](https://photos.app.goo.gl/h4KzTRQk3ARzJFYz8)

**Comment by majora2007** [comment] 2021-11-08 16:54
Okay understand it now. It's grouping together and treating it as a duplicate. Very interesting, shouldn't be hard to fix. 

I've slotted it for this upcoming release. Don't close the issue. It will be closed when released in a nightly for beta users to test.

**Comment by majora2007** [comment] 2021-11-08 17:50
Fixed locally, will be coming out with an upcoming nightly if you want to try it out, else please wait for v0.4.9.

Thanks for reporting, I totally missed a single line of code when I implemented partial volume support 2 releases ago. :)

![image](https://user-images.githubusercontent.com/735851/140792500-bf649f71-5350-4aed-943c-a661907175cd.png)

**Closed** 2021-11-09 12:51 UTC
Labels: bug, Parser
