### ISSUE TITLE
Missing pane

### ISSUE THREAD

**Issue by Sulframus** [Kareadita/Kavita#1470] opened 2022-08-23 20:34 UTC
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
The side nav for changing libraries is missing when changing moving from Setup to Kavita.

**To Reproduce**
1. Create a new user
2. Click Setup
3. Click on Kavita logo on the top left
4. See missing side nav

**Expected behavior**
Side nav will be accessible

**Screenshots**
![image](https://user-images.githubusercontent.com/50105122/186261509-d9921493-e35d-43b1-bcb1-93004a27f281.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Brave
 - Version 0.5.5.9

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majora2007** [comment] 2022-08-23 21:53
Where is the error you speak of? I'm not understanding what the issue is nor how to reproduce it.

**Comment by Sulframus** [comment] 2022-08-24 16:33
Updated the issue with the correct term.

**Comment by majora2007** [comment] 2022-08-25 14:57
I'm not able to reproduce, when I hit setup, Kavita moves me to the Register screen automatically.

**Comment by majora2007** [comment] 2022-08-28 15:28
I'm closing this out since no steps to reproduce have been provided. If you want to reopen and provide, please do.

**Closed by majora2007** 2022-08-28 15:28 UTC
Labels: can't reproduce
