### ISSUE TITLE
Mobile book reading not scrolling to saved progress point.

### ISSUE THREAD

**Issue by therobbiedavis** [Kareadita/Kavita#1163] opened 2022-03-18 13:57 UTC
**Describe the bug**
Book reader does not scroll to proper saved point on mobile.

Mobile - Saves progress but doesn't scroll to saved point.
Desktop - Saves progress and scrolls to saved point.

I tested this by scrolling to a certain point on desktop, and trying on desktop and mobile.
Desktop scrolls to around the same saved point, mobile doesn't.

I think tried scrolling to a different point on mobile, and retrying on desktop and mobile.
Desktop scrolls to around the saved point, mobile again doesn't.

**To Reproduce**
1. Open a book on mobile.
2. Scroll to any spot. Wait for save progress. Close book
3. Open book on desktop. See scrolling. Close book.
4. Open book on mobile. See no scrolling.

**Expected behavior**
Mobile should scroll to saved progress point

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Version: 0.5.1.32

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: 15.4
 - Browser: Chrome & Safari

**Comment by majora2007** [comment] 2022-03-27 12:47
This was closed in nightly

**Closed by majora2007** 2022-03-27 12:47 UTC
Labels: bug, needs-triage

**Comment by majora2007** [comment] 2022-03-30 13:40
Robbie meantioned this is still occurring on nightly, however on FF I cannot reproduce.

**Comment by majora2007** [comment] 2022-04-01 13:58
This is now fixed. It was a timing issue on Webkit browsers.
