### ISSUE TITLE
Pages getting skipped in 2 column layout for epub files

### ISSUE THREAD

**Issue by FireFtw** [Kareadita/Kavita#2044] opened 2023-06-07 17:36 UTC
**Describe the bug**
If the final page of a chapter comes up on the right-hand side of the 2 columns it will occasionally be skipped entirely. Navigating backwards will bring up the skipped page, but it will skip a different page before to get back to the beginning of the chapter. 

This seems to have something to do with margin percentage. For the chapter I'm using it will only behave like this if the margin is 15% or greater, while turning it down prevents it from happening.

**To Reproduce**
* Open a epub file with chapters (it seems to be more prevalent for books with shorter length chapters)
* Set the layout mode to 2 columns and turn the margin to 15% or greater (you might need to play around with the percentages a bit). 
* Go forward in pages until a new chapter, after landing at the beginning of a chapter navigate one back and check if the right columns text has been skipped when moving forward. This is repeatable, going to the original chapter and moving forward until the next chapter will behave the same.

**Desktop**
 - OS: Docker (latest)
 - Browser: Able to repeat on up to date Firefox and Chrome

**Comment by majora2007** [comment] 2023-07-03 17:07
What version of Kavita did this happen on? In v0.7.3, the margin code was updated slightly. Can you please add version along with an image

**Comment by FireFtw** [comment] 2023-07-03 18:57
> What version of Kavita did this happen on? In v0.7.3, the margin code was updated slightly. Can you please add version along with an image

I am on 0.7.3.1.

Here's an example, excuse the darkness.
https://youtu.be/mgE3sUmYcrE

**Comment by Arqueronet** [comment] 2023-07-05 15:44
It happens to me too and it's quite uncomfortable.
I think it has nothing to do with margins, I use 5% and still happens. I think it has to do with the fact that the number of pages in the chapter is odd (depending on the margin setting, the number of pages can change, but it's something collateral) and the two columns layout.
Same version: 0.7.3.1

**Comment by majora2007** [comment] 2023-07-06 20:55
Anyone want to send me a file and some pages and resolution so I can try to reproduce? Because on my files I'm not seeing anything like this.

**Comment by FireFtw** [comment] 2023-07-07 22:12
> Anyone want to send me a file and some pages and resolution so I can try to reproduce? Because on my files I'm not seeing anything like this.

Check your email.

**Comment by majora2007** [comment] 2023-07-08 15:02
I was able to reproduce with FireFtw's file and fix it on that. It will be released with v0.7.4.

**Comment by majora2007** [comment] 2023-07-10 16:50
This will be released in v0.7.4.

**Comment by Arqueronet** [comment] 2023-07-12 16:10
Still happening in 7.4...

When chapter pages are odd the last one is skipped, must turn back from new chapter to see it at right column.

It is exactly as seen in the video that FireFtw uploaded some days ago.

And very easy to reproduce.

The expected behavior is that the last page of chapter is seen on the left column and the right column is empty

**Comment by Arqueronet** [comment] 2023-10-31 11:36
Kindly reminder that in 0.7.10.2 bug still present.

**Comment by Hobogrammer** [comment] 2023-11-05 01:49
I was able to reproduce this error and I think I have a simple fix for it. Will create a PR once I see about writing a test.

**Closed** 2023-11-09 14:11 UTC
Labels: bug, UI
