### ISSUE TITLE
Mangaupdates icon is bypassing cache check

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2281] opened 2023-09-10 22:54 UTC
**Describe the bug**
`API.Services.ImageService Kavita has already tried to fetch from https://www.mangaupdates.com and failed. Skipping duplicate check`

**To Reproduce**
1. Go to series page
2. See broken icon for mangaupdates

**Expected behavior**
Check local cache so it doesn't pull from internet. 

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: N/A
 - Version: 0.7.8.1

**Comment by majora2007** [comment] 2023-09-15 16:08
Just tested on the latest nightly and cannot reproduce. Can you delete any cached favicon you might have and retry?

**Comment by DieselTech** [comment] 2023-09-15 21:04
Deleted the cached icons in the `favicons` folder. No change. 

![image](https://github.com/Kareadita/Kavita/assets/30128380/5e610afe-5884-4757-9ecd-87434dd4d188)

**Comment by DieselTech** [comment] 2023-10-12 04:45
Update: Have it working using a favicon named `mangaupdates.com.webp` instead of `www.mangaupdates.com.webp` like it was using in the past and is what was stored in the favicon folder.

 The /api/image/web-link endpoint would give error 400 if you tried to pass `www.mangaupdates.com` to it.

**Comment by majora2007** [comment] 2023-10-12 10:34
Going to close this out. The www might have been from an earlier nightly bug.

**Closed as completed** 2023-10-12 10:34 UTC
Labels: needs-triage
