### ISSUE TITLE
Volume title in volumes page use random chapter's title

### ISSUE THREAD

**Issue by lifegpc** [Kareadita/Kavita#1485] opened 2022-08-27 04:46 UTC
**Describe the bug**
Volume title in volumes page use random chapter title.

**To Reproduce**
1. Scan the library. (The file struct: [File Struct.zip](https://github.com/Kareadita/Kavita/files/9437308/File.Struct.zip). `comic_info` filed is readed from `ComicInfo.xml` which embed in cbz file.)
2. Open the series and see volumes.

**Expected behavior**
Voulme name is the name of first chapter in that volume. (In this case, the name of the volume 1 should be `心爱来袭`)

**Screenshots**
![image](https://user-images.githubusercontent.com/41434272/187014346-b19a8cfa-5057-4f1b-869f-9d334a5c99a3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 104.0.5112.102

**Additional context**
I have look to the database, it seems use the chapter's id in the database.
![image](https://user-images.githubusercontent.com/41434272/187014726-c10463dd-446e-44e9-924a-01f09c3af469.png)

**Comment by majora2007** [comment] 2022-09-12 14:22
Chapter Id does not dictate it's order. I'll take a look and ensure it's taking the first Chapter's title for the given Volume.

**Comment by majora2007** [comment] 2022-09-13 19:23
I have validated on my end, that the first chapter in a Volume get it's title shown:
![image](https://user-images.githubusercontent.com/735851/189991242-2168ee03-22dc-44f9-a056-5398b0b1301b.png)

I'm not able to reproduce this issue.

**Comment by majora2007** [comment] 2023-03-02 03:19
Going to close this issue. If it's still present, please comment and I'll reopen to investigate.

**Closed by majora2007** 2023-03-02 03:19 UTC
Labels: can't reproduce
