### ISSUE TITLE
Problem with names in Ebooks

### ISSUE THREAD

**Issue by Dunkler2Engel** [Kareadita/Kavita#1224] opened 2022-04-19 16:37 UTC
Hi,
i have the lastest version 0.5.2.0, and when i order the ebooks if a serie has Volume 0 add it in other serie.

Monster Girl Doctor - Volume 01 [Seven Seas][KindleHQ]
Monster Girl Doctor - Volume 02 [Seven Seas][KindleHQ]
Monster Girl Doctor - Volume 03 [Seven Seas][KindleHQ]

If is this order it well in a collecion, but with this 

Monster Girl Doctor - Volume 00 [Seven Seas][Kobo]

Make a new one, is any form to add the same series?

Other thing is when the Vol have a .5 like this

Monster Girl Doctor - Volume 01 [Seven Seas][KindleHQ]
Monster Girl Doctor - Volume 02 [Seven Seas][KindleHQ]
Monster Girl Doctor - Volume 02.5 [Seven Seas][KindleHQ]
Monster Girl Doctor - Volume 03 [Seven Seas][KindleHQ]

In this case, el 2.5 go to the bottom, is any way to put in the correct order?

Another thing not related with this, but in windows version the forlder of Kavita has more tha 400 files, and the most of them are dll files, Can be possible to add all of the in one folder named dll, an clean the first view of the folder?

**Comment by majora2007** [comment] 2022-04-19 17:26
Hi Dunkler, Volume 0 is not supported in Kavita as that is reserved for loose leaf chpaters in Manga.

First off, filename parsing doesn't do much in ebooks as epubs have metadata builtin, so you need to update the metadata within it. You can find details on the tags on our wiki:
https://wiki.kavitareader.com/en/guides/managing-your-files/ebooks

I would use Vol 0.1 or Volume 0.5. You could also try to use some way to force it into special, i think someone in the discord did that. I haven't tried it yet, so not sure exactly how to do with epub.

For your second question, no.

**Comment by Dunkler2Engel** [comment] 2022-04-30 02:51
Hi!, I have try with metadata in calibre and is a mess when i put  a Series with name and number this happen...
[https://imgur.com/a/zSl5vNG](url)

The problem is that one of the epubs are Epub3, and Others Epub2.

14,16,17,18,19,20,21,22,23,24,25 Are Epub3
1,2,3,4,5,6,7,8,9,10,11,12,13,15 Are Epub2

In the epub2 with calibre in "content.opf" put  this..

  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
    <dc:title>Accel World, Vol. 01: Kuroyukihime’s Return</dc:title>
    <dc:creator opf:role="aut" opf:file-as="Kawahara, Reki &amp; HIMA">Reki Kawahara</dc:creator>
    <dc:creator opf:role="aut">HIMA</dc:creator>
    <dc:identifier id="uid">2653572037</dc:identifier>
    <dc:publisher>Yen Press</dc:publisher>
    <dc:date>2017-10-30T23:00:00+00:00</dc:date>
    <dc:rights>© REKI KAWAHARA/KADOKAWA CORPORATION ASCII MEDIA WORKS 2009</dc:rights>
    <dc:contributor opf:role="bkp">calibre (5.41.0) [https://calibre-ebook.com]</dc:contributor>
    <dc:language>en</dc:language>
    <dc:identifier opf:scheme="calibre">5e99a97c-5d95-47c9-b148-65a74f8bf7b6</dc:identifier>
    <meta name="cover" content="cover"/>
    <meta name="calibre:title_sort" content="Accel World, Vol. 01: Kuroyukihime’s Return"/>
    **<meta name="calibre:series" content="Accel World"/>
    <meta name="calibre:series_index" content="1.0"/>**
    <meta name="calibre:author_link_map" content="{&quot;Reki Kawahara&quot;: &quot;&quot;, &quot;HIMA&quot;: &quot;&quot;}"/>
  </metadata>

But in Epub3 put:
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" xml:lang="en" unique-identifier="pub-id" prefix="calibre: https://calibre-ebook.com">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf" xmlns:calibre="http://calibre.kovidgoyal.net/2009/metadata">
    <dc:title id="id">Accel World, Vol. 14: Archangel of Savage Light</dc:title>
    <dc:creator id="id-1">Reki Kawahara</dc:creator>
    <dc:creator id="id-2">HIMA</dc:creator>
    <dc:rights>English translation © 2018 by Yen Press, LLC</dc:rights>
    <dc:identifier>calibre:29</dc:identifier>
    <dc:identifier>uuid:12af5052-8516-4cc7-9729-28ec83be7239</dc:identifier>
    <dc:identifier id="pub-id">urn:uuid:32cae782-19dd-4723-98bb-5cb5fd46a482</dc:identifier>
    <dc:language>en</dc:language>
    <dc:date>2018-06-26T00:00:00+00:00</dc:date>
    <dc:publisher>Yen Press</dc:publisher>
    <opf:meta refines="#id" property="title-type">main</opf:meta>
    <opf:meta refines="#id" property="file-as">Accel World, Vol. 14: Archangel of Savage Light</opf:meta>
    <meta name="cover" content="cover"/>
    <opf:meta refines="#id-1" property="role" scheme="marc:relators">aut</opf:meta>
    <opf:meta refines="#id-1" property="file-as">Kawahara, Reki</opf:meta>
    <opf:meta refines="#id-2" property="role" scheme="marc:relators">aut</opf:meta>
    <opf:meta refines="#id-2" property="file-as">HIMA</opf:meta>
    **<opf:meta property="belongs-to-collection" id="id-3">Accel World</opf:meta>
    <opf:meta refines="#id-3" property="collection-type">series</opf:meta>
    <opf:meta refines="#id-3" property="group-position">14</opf:meta>**
    <opf:meta property="calibre:author_link_map">{"Reki Kawahara": "", "HIMA": ""}</opf:meta>
  </metadata>

In the Epub2, calibre adds X.0, and this .0 is that cause of thw worng order in Kavita, if you edit the epub and remove this .0 the order shows well in Kavita.

This is a problem of Calibre or kavita? Is be possible to ignore this .0 in Kavita to order well whitout touch anything?

**Comment by Dunkler2Engel** [comment] 2022-05-02 18:15
@majora2007 
Did you see my last message? It is not to bother, it is more than anything curiosity, to know if you know where the error is to see if I can fix it and leave the perfect ebook collection.
I think it is because of the caliber that X.0 uses to be able to put books such as 1.5 and the like, but I have not found an option in the caliber to put integers without decimals

**Comment by majora2007** [comment] 2022-05-18 12:56
Okay I understand the issue. I moved this to next release due to the scope of the changes that might be required and where we are in the current release. We are looking into it though.

**Comment by therobbiedavis** [comment] 2022-05-18 13:11
Hi @Dunkler2Engel, I've just tested this and am unable to reproduce on our latest nightly (which it may have been fixed in already). In the image below the ones highlighted in white are epub 3, the rest are epub 2.

![image](https://user-images.githubusercontent.com/7907265/169046624-31f2670f-c49c-4d8c-95f9-df13e5c9d23e.png)

**Comment by Dunkler2Engel** [comment] 2022-05-22 00:35
Yes in the new version 0.5.3 the problem with the order when the volume has a X.5 is fixed

But the problem of mixing Epubs2 and Epubs3 is still there, I don't know if I can add some links with the epubs to display, but the problem I think is that I said it before. 
I do not know if it can be done but an easy solution is that when it is an epub3 to the series numers add a .0

**Comment by majora2007** [comment] 2022-05-22 13:03
I'm not sure I'm understanding what the issue with the epub2 and 3 mixing as Robbie reproduced and it is working as expected.

**Comment by damomato** [comment] 2022-06-20 03:50
> First off, filename parsing doesn't do much in ebooks as epubs have metadata builtin, so you need to update the metadata within it.

Hi Majora, is it possible to preference filename parsing over epub metadata? I don't use calibre so am not able to update metadata so was hoping Kavita could use the file name of 'Author - Series Name Series Number - Book Name' for the attributes. I'm able to name the books this was in Readarr, but not update metadata without Calibre.

**Comment by majora2007** [comment] 2022-06-20 11:32
@damomato no it is not. If you can't use calibre, you can manually edit as epubs are just zip files with an xml file for metadata.

**Comment by damomato** [comment] 2022-06-20 11:43
@majora2007 thanks. Maybe I should just bite the bullet and install Calibre. It's pretty annoying because the only reason I need it is for automatically writing/updating EPUB metadata for books I download in Readarr. I wish there was a better solution to have that automated.

**Comment by majora2007** [comment] 2022-06-20 11:45
@damomato you're in the same shed as me and a lot of other people. There really is nothing better to do this.

**Comment by damomato** [comment] 2022-06-28 01:23
@majora2007 editing embedded metadata isn't a planned feature for Kavita? I assume not possible or outside the scope?

**Comment by majora2007** [comment] 2022-06-28 01:48
@damomato that is correct. It is not a planned feature. It's not in scope of my vision.

**Comment by damomato** [comment] 2022-06-28 02:01
@majora2007 fair enough. It's a shame but understandable. Readarr should really have the functionality for this (without Calibre) but it's also not a planned feature

**Comment by adamcfe** [comment] 2022-06-29 20:52
> @damomato no it is not. If you can't use calibre, you can manually edit as epubs are just zip files with an xml file for metadata.

Hi Majora, I was thinking about opening a new issue but my problem seems relevant here. I noticed a funny behaviour with multi-author EPUBs: 

There is a book about languages invented by Tolkien written by 2 authors, Dimitra Fimi and Andrew Higgins. Kavita sees them as 4 persons: 
- R. R. Tolkien
- J.; Fimi
- Dimitra; Higgins
- Andrew

I checked other places:
- In calibre, they're correctly listed as "Dimitra Fimi & Andrew Higgins"
- The metadata.opf file includes two lines, listing them separately without any issues:
`<dc:creator opf:file-as="Fimi, Dimitra &amp; Higgins, Andrew" opf:role="aut">Dimitra Fimi</dc:creator>`
`<dc:creator opf:file-as="Fimi, Dimitra &amp; Higgins, Andrew" opf:role="aut">Andrew Higgins</dc:creat>`
- The EPUB's content.opf file is apparently the culprit, listing 3 authors:
`<dc:creator opf:role="aut" opf:file-as="Tolkien, J.R.R.">R. R. Tolkien, J.; Fimi, Dimitra; Higgins, Andrew</dc:creator>`. This explains why Kavita parsed it as 4 comma separated names. 

So while preferring filename parsing over EPUB parsing may not be desirable, it might be useful to increase the priority of the OPF files above the EPUBs they describe. After all, this is where calibre stores the metadata that we edit and want to see in Kavita. 

If it would be better to open a bug report, I'll be happy to do so. Btw, love Kavita, it's fantastic and does its job amazingly well.

**Comment by majora2007** [comment] 2022-06-29 21:40
@adamcfe Kavita will always use what is inside the epub aka content.opf as the metadata for an epub. We do not and I have no plans to support sidecar opf files.

Please note that Kavita separates on , and not ;. This might be a bug though, so it might be worth creating an issue after you validate per the spec.

**Comment by damomato** [comment] 2022-07-27 05:05
Majora I've taken your advice and ended up installing Calibre (LS docker version) in order to download and embed metadata and that's working much better. I only had one problem where the cover image wasn't updating and I had to delete the file and rescan before adding it back to fix. It sounds like this is being addressed in the next version though.

I'm still not linking Calibre to Readarr, just using it to do conversions and embed metadata. It's a shame there's no program that can scan a book library and do all that, but this is working well for now.

**Closed** 2022-11-05 11:42 UTC
Labels: discussion
