### ISSUE TITLE
[Epub reader] Margin issue in column mode

### ISSUE THREAD

**Issue by scare376** [Kareadita/Kavita#1734] opened 2023-01-09 03:00 UTC
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Books with a nested indent can have the characters overlap into other pages.

**Describe the bug**

**To Reproduce**
1. Add a book that has paragraphs with a nested indent.
2. Set reader to use column mode.
3. Some of the pages will have characters bleed over into another page.

**Expected behavior**
No character bleed into another page.

**Screenshots**
![image](https://user-images.githubusercontent.com/2068470/211234183-8a86e52f-f0e0-401f-b7cd-4146ca5f3188.png)
Characters bleed from next page.
![image](https://user-images.githubusercontent.com/2068470/211234348-981fa220-0f19-4d69-918c-9f2b693328d9.png)
Same characters with scroll mode turned on.
![image](https://user-images.githubusercontent.com/2068470/211234397-ce449b3b-b4b0-4c75-830f-a3d35ce53028.png)
Indent that was found in the book.

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Opera GX
 - Version: 0.6.1.22

**Additional context**
I already sent Joe the book that I'm having this issue on and am referencing here but I will send it again if needed.

**Comment by majora2007** [comment] 2023-01-09 13:49
Book Series title: くま クマ 熊 ベアー

**Comment by majora2007** [comment] 2023-03-11 18:53
Looks like we can close this issue out now that we have the appropriate vertical reading mode in the epub reader, which is how this book was intended to be read.

**Comment by majora2007** [comment] 2023-03-11 18:53
Looks like we can close this issue out now that we have the appropriate vertical reading mode in the epub reader, which is how this book was intended to be read.

**Closed** 2023-03-11 19:00 UTC
Labels: needs-triage
