### ISSUE TITLE
StoryArcNumber and Manual Sorting not respected in auto-generated reading list from ComicInfo.xml

### ISSUE THREAD

**Issue by ComputerWolf** [Kareadita/Kavita#1970] opened 2023-05-08 19:29 UTC
**Describe the bug**
`StoryArcNumber` is not respected when used in a auto-generated reading list from ComicInfo.xml and reverts to original order after manually sorting.

**To Reproduce**
 - Populate `StoryArc` and `StoryArcNumber` fields to existing files.
 - Scan and generate the reading list
 - List is not in `StoryArcNumber` order
 - Re-order the list manually to the proper order
 - After some time the list reverts to the original, wrong, order

**Expected behavior**
Reading list uses `StoryArcNumber` for ordering and maintains custom order on re-sort.

**Screenshots**
In this example, "The Clone Conspiracy #&#x2060;1" should be before "The Amazing Spider-Man #&#x2060;20", but #&#x2060;20 is re-sorted to the top of the list even after manually sorting.

![clone conspiracy 1 xml](https://user-images.githubusercontent.com/207052/236913641-4577b83c-9944-454e-b2d1-5cc6ccccf363.png)

![Issue 20 xml](https://user-images.githubusercontent.com/207052/236913679-ea901213-9738-4807-b618-7f37caa793c5.png)

![incorrect order](https://user-images.githubusercontent.com/207052/236913718-629e7703-cb26-4e20-a66f-e9d8ab9a9c05.png)

**Desktop (please complete the following information):**
 - OS: Windows - Scoop
 - Browser: Chrome 113.0.5672.64
 - Version: 0.7.2.0

**Comment by majora2007** [comment] 2023-05-13 18:10
I can't reproduce this when there is at least no existing list and we are scanning and adding new items, as long as the item has a number. 

I'll test with an existing list and see if I can reproduce that way.

**Comment by majora2007** [comment] 2023-06-07 15:43
I wasn't able to reproduce. Perhaps you can validate on the latest version which had some changes in how reading lists were generated with StoryArcNumbers and confirm.

**Comment by ComputerWolf** [comment] 2023-06-07 15:56
> I wasn't able to reproduce. Perhaps you can validate on the latest version which had some changes in how reading lists were generated with StoryArcNumbers and confirm. 

Sure I will update and report back. Thanks!

**Comment by majora2007** [comment] 2023-06-17 15:00
Closing for now. Feel free to comment if it's still an issue and I can try to reproduce again.

**Closed by majora2007** 2023-06-17 15:00 UTC
Labels: can't reproduce
