### ISSUE TITLE
Smart Filter is always sorted by Descending order

### ISSUE THREAD

**Issue by X-Xadro** [Kareadita/Kavita#2481] opened 2023-12-05 23:50 UTC
I'm using the Docker version provided by linuxserver: lscr.io/linuxserver/kavita:latest and i got the latest hotfix as well

Since the new (big) update none of my (smart) filters remember how the list should be sorted.

Example:

Making a new filter sorting by Sort Name Ascending (Arrow Up) works fine it's sorted A to Z (after clicking Apply)

When i save this Filter refresh the page and pick said Smart Filter its sorted Z to A and when i open the filter settings the Sort By arrow is down.

URL after Applying filter and then Saving it:
`/library/5?name=test&stmts=comparison%253D0%25C2%25A6field%253D18%25C2%25A6value%253D652%EF%BF%BDcomparison%253D0%25C2%25A6field%253D19%25C2%25A6value%253D5&sortOptions=sortField%3D1%C2%A6isAscending%3DTrue&limitTo=0&combination=1`

URL After loading this Smart Filter
`all-series?name=test&stmts=comparison%253D0%25C2%25A6field%253D18%25C2%25A6value%253D652%EF%BF%BDcomparison%253D0%25C2%25A6field%253D19%25C2%25A6value%253D5&sortOptions=sortField%3D1%C2%A6isAscending%3DTrue&limitTo=0&combination=1`

**Comment by majora2007** [comment] 2023-12-09 22:54
I can't reproduce this, but it's likely you're smart lists may be been affected by the issues that were fixed in v0.7.11. As mentioned in the changelog, there were a few bad bugs in the smart filters and I attempted to write some automatic migrations, but some might be broken. 

You might need to rebuild them. You can always check in the Smart Filters screen (accessed under user setting nav item) and if you see red, it's totally borked.

**Comment by X-Xadro** [comment] 2023-12-10 01:20
I did a complete fresh install of the latest version and the only thing i did was add 1 folder of my ebook library and created a Smart Filter.

![2023-12-10 02_15_00-Kavita - FanFiction — Mozilla Firefox Private Browsing](https://github.com/Kareadita/Kavita/assets/87056274/49ce5d52-7d24-456f-b3b0-8bf575f0f1fd)

And then when i went to look up this filter through the new Smart Filter page it shows like this

![2023-12-10 02_15_29-Kavita - test_1 — Mozilla Firefox Private Browsing](https://github.com/Kareadita/Kavita/assets/87056274/802e7720-0968-403b-bd86-3daef703ce20)

**Comment by X-Xadro** [comment] 2023-12-10 12:39
I reverted back to lscr.io/linuxserver/kavita:0.7.10 with my current database and all my smart filters work as it should.

**Comment by majora2007** [comment] 2023-12-10 13:45
Okay I misunderstood what you were having an issue with. The issue is that after loading a filter with ascending sort, the ascending sort doesn't load correctly. 

For future reference, please fill out the template which asks for detail steps to reproduce. It would have saved all of us a lot of time.

**Closed as completed** 2023-12-10 18:47 UTC
Labels: bug
