### ISSUE TITLE
BUG - Summary not being scanned in

### ISSUE THREAD

**Issue by fogame234** [Kareadita/Kavita#1130] opened 2022-03-01 01:00 UTC
**Describe the bug**
Summary will not load when being scanned from a metadata file on a new series. Created the comicinfo.xml file with Manga Manager created by user Promidiu in discord. All other metadata is scanned in. 

**To Reproduce**
1. Add series to library location
2. Scan library
3. Validated metadata information
4. All metadata is scanned in but the summary

**Expected behavior**
Summary to load and show with all other metadata

**Screenshots**
Not sure what screenshots to include but can include upon request 

**Desktop (please complete the following information):**
 - OS: Linux Docker
 - Browser Firefox
 - Version Stable 5.1.1

**Additional context**
I also removed an existing series and rescanned it back in. Same issue. No summary was added but all other metadata was. I have confirmed it isn't an issue with Promidiu's app.

**Comment by majora2007** [comment] 2022-03-27 19:02
I can't reproduce this on v0.5.1.36. The summary was imported on first load. Is this something you're still facing? Could you send me the xml as I haven't seen any issues of this.

**Comment by majora2007** [comment] 2022-05-13 17:53
Closing this because I'm pretty sure you're not having this issue anymore. Re-open if you are.

**Closed by majora2007** 2022-05-13 17:53 UTC
Labels: can't reproduce
