### ISSUE TITLE
Bug searching for author 

### ISSUE THREAD

**Issue by hollisticated-horse** [Kareadita/Kavita#2455] opened 2023-11-25 07:47 UTC
**Describe the bug**
When searching for an author, and selecting from the proposed author names, I am being redirected to my whole book collection, not the authors page. Seems I can't find an author's page. 

**To Reproduce**
1. Start in Home. 
2. Use the search bar to look up an author's name
3. Click on the name of the author when it appears in the drop down menu
4. You get sent to the whole library page. 

**Expected behavior**
Arrive on the page of the author, with a list of the books they wrote. 

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browse : Firefox 119.0.1
 - Version :     0.7.10.2

Same issue when clicking on the author name tag in a book page.

**Comment by scare376** [comment] 2023-11-25 08:10
This is a duplicate of #2386 and #2443 the issue has been resolved on nightly.

**Comment by hollisticated-horse** [comment] 2023-11-26 13:57
okay great, should I keep this open until update is rolled up on latest or should I close now @scare376 ?

**Comment by majora2007** [comment] 2023-11-26 13:58
You can close.

**Closed as completed** 2023-11-26 14:44 UTC
Labels: needs-triage
