### ISSUE TITLE
Renaming library cause all chapters to be marked as unread

### ISSUE THREAD

**Issue by MisterTeknis** [Kareadita/Kavita#2744] opened 2024-02-26 07:57 UTC
### What happened?

When a library gets the name changed all chapters under the library get marked as unread as if they are new files, even though the files on disk have not changed. 

### What did you expect?

Expected read status to be maintained across a library rename. 

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Firefox

### Additional Notes

Renaming the library back to the previous name does not fix the chapter read status.

**Comment by majora2007** [comment] 2024-02-26 12:08
Let me make sure I understand what happened. You setup a library, scanned, read a few things.

Then renamed the library, rescanned. Then all your series were unread?

Can you list your library root path and the series in question's names and file path?

What is more likely happening is you have the same series in different folders parallel to the library root and each scan Kavita is picking up a different one.

**Comment by MisterTeknis** [comment] 2024-02-26 19:44
Similar yes, I setup the library many months ago, over four thousand chapters were  read according to stats page, The container has been kept up to date since I initially set up the library. Unsure if that matters but more info. Scanning over these months has worked fine.

Initial Library name was Kai changed to Manga. Root folder unchanged.
Root path: /Secure/Media/Books/Kaizoku 
/Secure is mounted with docker on Unraid

A few of series paths that were marked as unread: 

/Secure/Media/Books/Kaizoku/Ballpark_de_Tsukamaete
/Secure/Media/Books/Kaizoku/Made_in_Abyss
/Secure/Media/Books/Kaizoku/Mashle_-_Magic_and_Muscles
/Secure/Media/Books/Kaizoku/The_Ancient_Magus_Bride

Every series in the library were marked unread, they all follow this folder structure.

All of the series are directly under the root path.
The series folder directly contains all the CBZ files without any other subfolders.

Hope that helps.

**Comment by majora2007** [comment] 2024-02-26 19:50
Interesting, I've never actually renamed my library name, but I can't imagine these chapters being marked as unread unless they were added/removed from a volume or removed then re-added into Kavita. 

I'll take a look into it and try to reproduce it.

**Comment by majora2007** [comment] 2024-03-08 20:42
Just following up here: When you say Library renamed, are you saying you change this? 
![image](https://github.com/Kareadita/Kavita/assets/735851/33cf3d06-8ad3-45df-bb14-6fe886d1d016)

**Comment by MisterTeknis** [comment] 2024-03-08 20:47
Yes, that is how I renamed it.

**Comment by majora2007** [comment] 2024-03-30 17:11
I'm not able to reproduce.

Before Rename:
![image](https://github.com/Kareadita/Kavita/assets/735851/131c420b-8b42-4cf3-a2ca-5eb7bc5494b0)

After Rename (and manual browser refresh):
![image](https://github.com/Kareadita/Kavita/assets/735851/4f23b7d4-7822-4274-83b9-10bc7c769567)

**Comment by majora2007** [comment] 2024-03-30 17:12
Please make sure you did not change the library type on accident. That can cause progress loss as it may interpret the filenames differently.

**Comment by MisterTeknis** [comment] 2024-04-02 03:48
I am not able to reproduce now either, certainly not going to complain about that. Sorry for the hassle.

**Closed as completed** 2024-04-02 10:54 UTC
Labels: can't reproduce
