### ISSUE TITLE
Excess space at bottom of page

### ISSUE THREAD

**Issue by thegreatestgiant** [Kareadita/Kavita#2482] opened 2023-12-06 14:11 UTC
Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
When I scroll down to the bottom of the page of a series, it keeps going far beyond the point it should have stopped and I'm left with a grey screen.

**To Reproduce**
1. Go to a library of books
2. Click on any series of epubs
3. Scroll down to the bottom of the page
4. See excess whitespace

**Expected behavior**
It to stop at a point where I can still see the books in the series and preferably the description of the series to

**Screenshots**
![image](https://github.com/Kareadita/Kavita/assets/96693544/c607b722-3265-4bc9-a913-438dec732c6f)
![image](https://github.com/Kareadita/Kavita/assets/96693544/0d120b8c-6b7d-4ca0-8ed7-51f6b61e514e)
![image](https://github.com/Kareadita/Kavita/assets/96693544/07bcf814-731c-477c-9d01-bd756d50fe5d)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: chrome on a chromebook
 - Version: 0.7.11.1

**Comment by majora2007** [comment] 2023-12-06 14:18
Duplicate of #2147

**Closed as completed by majora2007** 2023-12-06 14:18 UTC
Labels: needs-triage
