### ISSUE TITLE
PDF files cannot be read on docker/arm64 (Oracle Linux 8)

### ISSUE THREAD

**Issue by DjidaneJex** [Kareadita/Kavita#1393] opened 2022-08-02 07:14 UTC
**Describe the bug**
PDF files are shown as CANNOT READ on docker/arm64. Other files types (epub, cbz) are OK.

**To Reproduce**
1. Create a new docker container on arm64 platform
2. Create a library with a PDF file
3. View the library : the pdf file is shown as CANNOT READ and the file can't be opened.

**Screenshots**
Sample with an epub and a pdf file :
![image](https://user-images.githubusercontent.com/16526831/182314138-607ecc5c-2cbd-4edb-923c-f27b9224f360.png)

**Server :**
 - OS: Docker, arm64
 - Version : 0.5.4.0
 - Browser: Microsoft Edge

**Additional context**
No special configuration, the library have read/write permissions.

**Comment by majora2007** [comment] 2022-08-02 13:54
Do any PDFs work? If not, could you create an empty library of 1 PDF file, delete your logs and scan then attach said logs here so I can see the stack trace?

If they do, please reach out to me on discord and send me the PDF so I can test.

**Comment by majora2007** [comment] 2022-08-05 12:37
Thanks for the updated log, that indeed shows the issue. 

I see the issue, the release got rolled back. We added ARM x64 to the downstream library, but during a library update, we got updated to a stable and not the prerelease with our changes. Ill take care of it in this release.

**Comment by DjidaneJex** [comment] 2022-08-09 13:48
Thanks, but I think the issue is still present, I updated to the nightly version 0.5.4.18, and I still have errors, and PDF files can't be read : 
```
2022-08-09T15:41:00.0073958+02:00       WARN    [API.Services.BookService]      [0]     [BookService] There was a critical error and prevented thumbnail generation on /books/[REDACTED]. Defaulting to no cover imageSystem.DllNotFoundException: Unable to load shared library 'pdfium' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpdfium: cannot open shared object file: No such file or directory
   at Docnet.Core.Bindings.fpdf_view.__Internal.FPDF_InitLibrary()
   at Docnet.Core.Bindings.fpdf_view.FPDF_InitLibrary()
   at Docnet.Core.DocLib..ctor()
   at Docnet.Core.DocLib.get_Instance()
   at API.Services.BookService.GetPdfCoverImage(String fileFilePath, String fileName, String outputDirectory) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 911
```

**Comment by majora2007** [comment] 2022-08-10 13:50
Note to self, it looks like Docnet.Core v0.4.2-alpha 3+ breaks our specific patches. I have rolled back and will release a new version for testing.

**Comment by DjidaneJex** [comment] 2022-08-12 07:52
I updated to the version 0.5.4.21, but I still have the errors : 
```
2022-08-12T09:40:56.2034436+02:00       WARN    [API.Services.BookService]      [0]     [BookService] There was an exception getting number of pages, defaulting to 0System.DllNotFoundException: Unable to load shared library 'pdfium' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpdfium: cannot open shared object file: No such file or directory
   at Docnet.Core.Bindings.fpdf_view.__Internal.FPDF_InitLibrary()
   at Docnet.Core.Bindings.fpdf_view.FPDF_InitLibrary()
   at Docnet.Core.DocLib..ctor()
   at Docnet.Core.DocLib.get_Instance()
   at API.Services.BookService.GetNumberOfPages(String filePath) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 485
```

**Comment by majora2007** [comment] 2022-08-15 13:26
Hi, I had a team member test this locally, just the stable and nightly on their ARM x86 (Raspberry Pi) and he reported both was fine with creating cover images on PDFs. 

I'm already assuming, but I'd like to validate that you've validated your pdf works and have tried other PDFs, like ones downloaded off the web, work?

**Comment by DjidaneJex** [comment] 2022-08-15 14:06
Hi, yes, every PDF I have (20-30) have this error, the previous check was done on some of mine + the dummy pdf file from w3c.

Could you update the docnet library again ? I could try to swap the pdfium binaries on the last version to check if it works.

**Comment by majora2007** [comment] 2022-08-15 14:18
I have updated it back to the original (latest alpha), I'll ping on this ticket when it's merged into the latest nightly. It's just odd since it's docker and our team member wasn't able to reproduce. No other user has mentioned anything (and a lot of people use pdfs in Kavita), so I'm starting to think something weird is happening with your system. 

What's your OS? Is this a Pi?

**Comment by DjidaneJex** [comment] 2022-08-15 14:26
I'm using Oracle Linux 8 on an Oracle A1 Flex instance (Cloud Free Tier, Ampere Altra 80C CPU).

**Comment by DjidaneJex** [comment] 2022-08-18 21:02
I updated to the version 0.5.5.1, I still can't get it to work with the bundled or an updated version.
When I swap the pdfium.so file with one more recent (and restart the container), the scan seems to crash with no error message when it encounter the first pdf file.

**Comment by floreo** [comment] 2022-10-12 17:42
Hello,

I kinda have the problem with the docker version, PDF, epubs are not scrapped but mangas are.

Docker version: Docker version 20.10.18, build b40c2f
Kavita version: 0.5.6.0

I don't see any errors in the scanning [logs ](https://pastebin.com/bt34Mb2Z) but it's not scanning anything
I tried with the [dummy ebook](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf) that @DjidaneJex  mentionned.

Feel free to ask me more details if it lacks.
Thanks.

**Comment by vedhavyas** [comment] 2023-01-04 17:46
Hello,

I'm seeing the same issue. I have single pdf in a directory. But when I create a library and scan, nothing shows up.

Nothing in the logs as well. 
```
Jan 04 17:41:14 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:41:14.642 +00:00  66] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library responded 200 in 1.4559 ms 
Jan 04 17:41:14 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:41:14.796 +00:00  66] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library responded 200 in 1.1910 ms 
Jan 04 17:41:16 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:41:16.014 +00:00  66] [Information] API.Services.TaskScheduler Enqueuing library scan for: 2 
Jan 04 17:41:16 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:41:16.015 +00:00  66] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/library/scan responded 200 in 1.8707 ms 
Jan 04 17:41:16 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:41:16.016 +00:00  41] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache & Temp directories 
Jan 04 17:41:16 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:41:16.016 +00:00  41] [Information] API.Services.Tasks.CleanupService Cache and temp directory purged 
Jan 04 17:41:16 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:41:16.017 +00:00  72] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Books 
Jan 04 17:41:16 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:41:16.019 +00:00  72] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished file scan in 0 milliseconds. Updating database 
Jan 04 17:41:16 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:41:16.036 +00:00  72] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished library scan of 0 series in 20 milliseconds for Books. There were no changes 
Jan 04 17:41:16 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:41:16.036 +00:00  72] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan 
Jan 04 17:41:16 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:41:16.036 +00:00  72] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 0 series that needs to be removed: [] 
Jan 04 17:41:16 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:41:16.036 +00:00  72] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan - complete 
Jan 04 17:41:16 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:41:16.180 +00:00  68] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library responded 200 in 1.3445 ms 
Jan 04 17:41:16 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:41:16.337 +00:00  70] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library responded 200 in 1.2134 ms 
Jan 04 17:44:29 hub hub[1800642]: kavita        | [Kavita] [2023-01-04 17:44:29.827 +00:00  77] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 0.8250 ms 
```
This is running in Docker on Ubuntu with AMD cpu though
Happy to share more details.

**Comment by majora2007** [comment] 2023-01-04 18:05
@vedhavyas You are likely not following the scanner requirements. Files must be in a folder from the library root or they will not be scanned. https://wiki.kavitareader.com/en/guides/managing-your-files/scanner#file-layout

This issue is specific to files not being openable on ARM. 

Btw, for those on this issue, there is a likely workaround for you:
Kavita doesn't seem to run or generate covers on my computer? at https://wiki.kavitareader.com/en/faq

**Closed** 2023-06-17 14:54 UTC
Labels: can't reproduce
