### ISSUE TITLE
Download not working for Firefox on iOS

### ISSUE THREAD

**Issue by mhbates** [Kareadita/Kavita#1365] opened 2022-07-06 16:37 UTC
**Describe the bug**
Clicking the download button in Firefox for iOS doesn't do anything; no download is initiated. The download button goes through its animation, it looks like the page loads or reloads, but no download takes place. As a test, I tried downloading with Safari and that worked.

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 15.5
 - Browser: Firefox Daylight 102.0 (11640)
 - Version: Kavita 0.5.4.0

**Comment by majora2007** [comment] 2022-07-08 21:20
@therobbiedavis can you take a look at this? I can confirm chrome and Firefox on Android work.

**Comment by majora2007** [comment] 2022-07-14 12:20
Looks to be an issue with our downstream library for handling downloads. I'll open an issue or look for a workaround.

**Comment by majora2007** [comment] 2024-02-10 20:16
Closing this out. Have validated on latest stable this is working. Put a warning when downloading over certain size for iOS devices, due to different devices having arbitrary sizes (not documented) that downloads just fail on.

**Closed by majora2007** 2024-02-10 20:16 UTC
Labels: bug, help wanted, UI
