### ISSUE TITLE
Special volume on loose leaf library are not grouping

### ISSUE THREAD

**Issue by Rivers47** [Kareadita/Kavita#3299] opened 2024-10-22 19:18 UTC
### What happened?

I have a library with a structure like this:

 - Manga title
    - Manga title vol n
      - image files
    - Specials
      - Manga title SP01
        - image files

The image files are separate single images.

There are 3 issues:
- Kavita does not group the special volume into a series, but inside showing each single image as a separate chapter. (Picture 3)
- sometimes the images are linked to the wrong file, despite ... -> info showing the correct file names. (Picture 1 and 3)
- For the volumes which does get grouped together, if I click on the thumbnail it shows a another "issues" tab where the volume is marked as "special" (picture 2). I'm not sure if this is intentional, maybe it's because I don't have any metadata. Also, no thumbnail is shown if I click into the "special" issue

![image](https://github.com/user-attachments/assets/793f9442-220d-4347-b41d-d1fad4d3c6cf)
![image](https://github.com/user-attachments/assets/0bb35a4c-feff-4236-ba06-a69cbef91060)
![image](https://github.com/user-attachments/assets/0c6258ee-9e83-4a09-8a49-162905066fdc)

### What did you expect?

At least the special files should be grouped into a single volume as organized in the directory structure.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

**Comment by majora2007** [comment] 2024-10-24 18:40
What's the library type? Manga or Image?

**Comment by hamdan7m** [comment] 2024-10-24 21:33
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Rivers47** [comment] 2024-10-25 14:11
> What's the library type? Manga or Image?

Comic, but I think Image has the same problem

**Comment by majora2007** [comment] 2024-10-25 14:45
But these are Manga, so Manga would be much better. Comic is made for American/French comics.

Like `Chapter 1` is better than `Issue #1` for Manga. 

Let me try on Comics and Image as well. I tried with Manga and couldn't reproduce.

**Comment by Rivers47** [comment] 2024-10-25 14:52
I see. I tried to remove the library and recreate it as Manga type but the problem persists.

**Comment by majora2007** [comment] 2024-10-25 14:58
For future reference you don't need to remove the library and recreate. You can just edit the library and change the type. There must be something in your directory structure that's not matching mine. 

This is how I have my files:
```
    "My Dress-Up Darling/My Dress-Up Darling vol 1/0001.png",
    "My Dress-Up Darling/My Dress-Up Darling vol 1/0002.png",
    "My Dress-Up Darling/My Dress-Up Darling vol 2/0001.png",
    "My Dress-Up Darling/Specials/My Dress-Up Darling SP01/0001.png"
```

**Comment by Rivers47** [comment] 2024-10-25 15:02
> For future reference you don't need to remove the library and recreate. You can just edit the library and change the type.

That's what I tried first but it failed so I thought maybe some internal cache persisted. Now the thumbnails are correct now, but every image in the special folder still shows as individual chapters.

This is my tree structure 
```
葬送のフィリーレン
├── Specials
│   └── 葬送のフリーレン 公式ファンブック SP01
├── 葬送のフィリーレン vol 1
├── 葬送のフィリーレン vol 10
├── 葬送のフィリーレン vol 11
├── 葬送のフィリーレン vol 12
├── 葬送のフィリーレン vol 2
├── 葬送のフィリーレン vol 3
├── 葬送のフィリーレン vol 4
├── 葬送のフィリーレン vol 5
├── 葬送のフィリーレン vol 6
├── 葬送のフィリーレン vol 7
├── 葬送のフィリーレン vol 8
└── 葬送のフィリーレン vol 9
```

where every folder contains just a bunch of images

**Comment by Rivers47** [comment] 2024-10-25 15:19
Just tried with a fresh container and same result..

**Comment by majora2007** [comment] 2024-10-27 13:33
Okay I understand what's happening. Before I wasn't testing enough. First, for image libraries, Image is the library type you should use. Everything else has extremely limited support and wont be enhanced or bugfixed. Image library type is for people that want to use loose leaf images (it's a rare way to collect files). 

The problem that is occurring is that Specials are not architected to be multi-part files mapping into one file. This would require quite a bit of work to rework to make work. I would ask you to open a feature request to support this. It's much too large an effort to be done within a single bugfix (I need more community request for it). 

When you create the request, link it to this issue, so we can close this issue out but retain the knowledge.

**Comment by Rivers47** [comment] 2024-10-27 17:18
OK, thanks for the answer.
Honestly I don't understand why most comic server/tooling centres around the idea that one print exists as one file, considering the fact most image file formats are not compressible. For video servers you'd never expect, say 12 episodes of an anime, to be grouped into a zip. I guess it comes from the ancient time when accessing hundreds of individual files on hard disk is slower than reading a single file.
How much work would be needed to use comicinfo on a directory?

**Comment by majora2007** [comment] 2024-10-27 17:45
From what I've seen, almost all tooling and all releases are in archive format, plus it's just much easier to move files around, etc. Servers are going to build what is the most general case. For example, I was going to remove image support but enough of the community voiced their opinions that I sat down and revamped it the best I could with how Kavita functions. 

Sidecar files (aka loose comicinfo files etc) is not something I would consider to solve this and nor am I a fan of.

**Closed as completed** 2024-11-08 20:06 UTC
Labels: enhancement, Parser, Scanner
