### ISSUE TITLE
FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by losslesspng** [Kareadita/Kavita#2747] opened 2024-02-26 20:03 UTC
### What happened?

Error during library scan

### What did you expect?

Constantly seeing this error during library scans on the Comics library. 

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Other (List in "Additional Notes" box)

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
INSERT INTO "PersonSeriesMetadata" ("PeopleId", "SeriesMetadatasId")
VALUES (@p0, @p1);
[Kavita] [2024-02-26 10:01:52.239 -05:00  56] [Error] Microsoft.EntityFrameworkCore.Update An exception occurred in the database while saving changes for context type 'API.Data.DataContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
```

### Additional Notes

Using Opera GX as main browser for accessing Web UI.

**Comment by Roshri** [comment] 2024-02-27 18:29
I'm having a similar issue so I'm adding context from my case:

I noticed  this happened on a series that has a bad match. It appears duplicated.
Both Magical Girl Apocalypse and Magical Girl Site have metadata for Magical Girl Site
This repeated for other series with duplicated folders.

Another case where this happened was a series that shows a duplicate of the same volume (Sleepy Princess in the Demon Castle shows two volume 22s, none of which can be read using Kavita. Other files from the same series can be read normally)
![image](https://github.com/Kareadita/Kavita/assets/29184137/322911df-3a31-42b9-81a0-3550f0815098)

Tried removing the files from library root and scan, but error persists. When this error occurs I noticed the library loops back and starts a whole library scan again

This is the output on Kavita console

```[Kavita] [2024-02-27 15:25:13.553 -03:00  58] [Information] API.Services.Tasks.ScannerService Beginning file scan on Sleepy Princess in the Demon Castle
[Kavita] [2024-02-27 15:25:13.569 -03:00  58] [Error] API.Services.Tasks.ScannerService [ScannerService] There was an error trying to find and apply .kavitaignores above the Series Folder. Scanning without them present
System.Collections.Generic.KeyNotFoundException: The given key 'R:/Manga/Translated/Ongoing/Sleepy Princess in the Demon Castle' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at API.Services.Tasks.Scanner.ParseScannedFiles.BuildIgnoreFromLibraryRoot(String folderPath, IDictionary`2 seriesPaths) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ParseScannedFiles.cs:line 149
[Kavita] [2024-02-27 15:25:13.570 -03:00  58] [Debug] API.Services.DirectoryService [ScanFiles] called on R:/Manga/Translated/Ongoing/Sleepy Princess in the Demon Castle
[Kavita] [2024-02-27 15:25:13.570 -03:00  58] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 0 files for R:/Manga/Translated/Ongoing/Sleepy Princess in the Demon Castle
[Kavita] [2024-02-27 15:25:13.570 -03:00  58] [Information] API.Services.Tasks.ScannerService [ScannerService] R:/Manga/Translated/Ongoing/Sleepy Princess in the Demon Castle is empty or is no longer in this location
[Kavita] [2024-02-27 15:25:13.571 -03:00  58] [Information] API.Services.Tasks.ScannerService ScanFiles for Sleepy Princess in the Demon Castle took 17
[Kavita] [2024-02-27 15:25:13.798 -03:00  58] [Error] Microsoft.EntityFrameworkCore.Database.Command Failed executing DbCommand (1ms) [Parameters=[@p0='11369'], CommandType='"Text"', CommandTimeout='30']
DELETE FROM "Series"
WHERE "Id" = @p0
RETURNING 1;
[Kavita] [2024-02-27 15:25:13.799 -03:00  58] [Error] Microsoft.EntityFrameworkCore.Update An exception occurred in the database while saving changes for context type 'API.Data.DataContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
[Kavita] [2024-02-27 15:25:13.802 -03:00  58] [Fatal] API.Services.Tasks.ScannerService There was an error during ScanSeries to delete the series as no files could be found. Aborting scan
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at API.Data.UnitOfWork.CommitAsync() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Data\UnitOfWork.cs:line 92
   at API.Services.Tasks.ScannerService.CommitAndSend(Int32 seriesCount, Stopwatch sw, Int64 scanElapsedTime, Series series) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\ScannerService.cs:line 399
   at API.Services.Tasks.ScannerService.ScanSeries(Int32 seriesId, Boolean bypassFolderOptimizationChecks) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\ScannerService.cs:line 268```

**Comment by DieselTech** [comment] 2024-03-07 23:40
@Roshri Just want to confirm, what version of Kavita are you running?

**Comment by Roshri** [comment] 2024-03-08 00:41
Funny how you commented mere moments after I found another series with repeated volumes lol

I'm running stable 0.7.14.0

**Closed as completed** 2024-03-17 17:58 UTC
Labels: needs-triage
