### ISSUE TITLE
Unable to move to the next chapter of "Webtoon Reading Mode" in an Android environment

### ISSUE THREAD

**Issue by ytoaa** [Kareadita/Kavita#1942] opened 2023-04-23 14:03 UTC
For now this has been tested on Android 12 version and I don't know if it's the same problem with other versions. This symptom does not work the same with the touch, Bluetooth mouse connected. However, it is possible to scroll up to the previous chapter. To sum up, I'm having trouble with the motion of scrolling down on Android to the next chapter.
The installation environment is 0.7.1 for docker version
I also tried nightly builds, but the symptoms were the same.
Most importantly, it's reproduced on the demo site as well.

**Comment by majora2007** [comment] 2023-04-23 15:27
Please provide more information, like what type of phone you're using, if you see the continuous reader section to scroll into, the browser you're using. I can't help without that information.

**Comment by YTOAA** [comment] 2023-04-23 15:39
Samsung A90 5g 
In the video, it was tested with Firefox, but both edge and chromium have the same symptoms

**Comment by YTOAA** [comment] 2023-04-28 12:42
Is this problem intended in an Android environment?

**Comment by majora2007** [comment] 2023-07-10 19:34
No, it's not intended. I don't have this issue and I'm on an Android environment.

**Comment by ShivamAmin** [comment] 2024-04-25 22:03
I got this on ios Safari with kavita installed as a PWA. It's hard to consistently reproduce.

**Comment by DieselTech** [comment] 2024-07-23 20:12
This was listed as fixed in version 0.8.2:

> Fixed: Fixed a bug where on mobile devices the continuous scroller wouldn't trigger when scrolling on webtoon mode

If your still seeing this problem, please open a new ticket.

**Closed by DieselTech** 2024-07-23 20:12 UTC
Labels: UI, needs-triage, can't reproduce
