### ISSUE TITLE
'Include in Recommended' fails when 'Include in Dashboard' turned off

### ISSUE THREAD

**Issue by rosystain** [Kareadita/Kavita#1822] opened 2023-02-21 09:18 UTC
1. Go to 'Library Settings / Advanced'
2. Turn  'Include in Dashboard' off and left 'Include in Recommended' on.
3. Back to the Recommended Page.
4. On Deck disappeared and `Nothing to show here. Add some metadata to your library, read something or rate something. This library may also have recommendations turned off.` instead.

**Expected behavior**
The toggle of 'Include in Dashboard' should not affect the recommendations for the library's own Recommended Page

**Comment by majora2007** [comment] 2023-02-21 21:32
I'm not able to reproduce this. I see recommendations page fine and on deck and other normal dashboard feeds are missing items from that library.

**Comment by rosystain** [comment] 2023-02-22 04:48
On Deck in the main Dashboard is fine but On Deck in Recommendations Page is lost.

![Screenshot_20230222_121522](https://user-images.githubusercontent.com/27495128/220520782-6ef66e68-25f6-4da0-abfa-405515796d3f.png)

![Screenshot_20230222_121636](https://user-images.githubusercontent.com/27495128/220520792-2e8e0305-600d-4ac5-8b8d-76625f07f520.png)

I run Kavita 0.7.1.0  by using docker on UNRAID.
 
PS:  I noticed that changements in advanced will not be applied when creating a new library.

**Comment by majora2007** [comment] 2023-05-07 15:47
Can you reproduce this on v0.7.2?

**Comment by rosystain** [comment] 2023-05-07 19:06
I'm sorry I didn't make myself clear.
I would like to keep on deck in a separate library page, even if `Include in Dashboard` is set to off.
I thought it was a bug when I noticed that on deck disappeared with the setting is off. This may have caused a misunderstanding.

**Comment by majora2007** [comment] 2023-05-07 19:44
Okay, I did misunderstand. I'm going to close this out as it is a feature request and belongs on feats.kavitareader.com.

**Closed by majora2007** 2023-05-07 19:44 UTC
Labels: can't reproduce
