### ISSUE TITLE
ComicVine type library not scanning properly when using folders by Publisher (root/publisher/series folder layout is not working reliably) 

### ISSUE THREAD

**Issue by Roshri** [Kareadita/Kavita#3110] opened 2024-08-13 20:07 UTC
### What happened?

From Discord

My comicvine type library is not working properly when doing a normal scan.
It's currently set up like this
Comics/Publisher/SeriesName (Year) 

with Comics being the root folder for the library. When doing a normal scan it doesn't pick up new files, so I have to do a Force Scan every time I add something new

majora's answer

Yeah, it's work built upon that. When we scan, we take series paths and check them. But with this enhancement, when you use a Publisher folder and it has modifications, instead of saying "Scan Publisher", it will now do a "dirty check" to check all the known series within. 

But now that I'm talkinga bout it, there might be an edge case where there are new folders that Kavita might miss.

### What did you expect?

The normal scan should pick up new files (and folders)

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Firefox

**Comment by DieselTech** [comment] 2024-08-13 20:11
Here is the notes that I have on the scanner for the CV library type
I haven't gotten down to figuring out what is going on yet, just in the note taking phase:

```
[Kavita] [2024-07-16 18:23:41.234 -04:00  96] [Information] API.Services.TaskScheduler Enqueuing library scan for: 1
[Kavita] [2024-07-16 18:23:41.268 -04:00  96] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/library/scan?libraryId=1&force=false responded 200 in 67.0881 ms
[Kavita] [2024-07-16 18:23:41.360 -04:00  93] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Comics
[Kavita] [2024-07-16 18:23:41.388 -04:00  93] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library Comics Step 1: Scan Files
[Kavita] [2024-07-16 18:23:41.667 -04:00  93] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library Comics Step 1.A: Process 1 folders
[Kavita] [2024-07-16 18:23:41.667 -04:00  93] [Debug] API.Services.Tasks.ScannerService     [ScannerService] Library Comics Step 1.B: Scan files in /comics
[Kavita] [2024-07-16 18:23:41.673 -04:00  96] [Debug] API.Controllers.LibraryController Caching libraries for library_lsiotest
[Kavita] [2024-07-16 18:23:41.675 -04:00  96] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library/libraries responded 200 in 2.5990 ms
[Kavita] [2024-07-16 18:23:42.983 -04:00  89] [Debug] API.Controllers.LibraryController Caching libraries for library_lsiotest
[Kavita] [2024-07-16 18:23:50.046 -04:00  93] [Debug] API.Services.Tasks.ScannerService     [ScannerService] Library Comics Step 1.C: Process files in /comics
```

Almost 2 full days later the scan completes:

```
[Kavita] [2024-07-18 16:18:05.883 -04:00  93] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library Comics Step 4: Save Library
[Kavita] [2024-07-18 16:18:15.798 -04:00  93] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished library scan of 81365 files and 9672 series in 165274547 milliseconds for Comics
[Kavita] [2024-07-18 16:18:15.798 -04:00  93] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library Comics Step 5: Remove Deleted Series
[Kavita] [2024-07-18 16:18:16.284 -04:00  93] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan
[Kavita] [2024-07-18 16:19:41.747 -04:00  93] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 15 series that needs to be removed: ["Star Trek: The Next Generation: The Gorn Crisis (2001)","Star Trek: The Next Generation: Forgiveness (2001)","Albion (2005)","Majestic (2005)","Countdown (2000)","Manifest Eternity (2006)","Star Trek: The Next Generation: Embrace the Wolf (2000)","Star Trek: The Next Generation -- The Killing Shadows (2000)","Captain Atom: Armageddon (2005)","21 Down (2002)","Planetary/The Authority: Ruling the World (2000)","The X-Files/30 Days of Night (1)","Planetary: Crossing Worlds (2004)","Star Trek: The Next Generation - Enemy Unseen (2001)","Planetary (1999)"]
[Kavita] [2024-07-18 16:19:41.756 -04:00  93] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan - complete
[Kavita] [2024-07-18 16:22:35.991 -04:00  29] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache directories
[Kavita] [2024-07-18 16:22:35.991 -04:00  29] [Information] API.Services.Tasks.CleanupService Cache directory purged
```

Once the scan was done I started a new scan the next day:
```
[Kavita] [2024-07-19 17:49:51.471 -04:00  80] [Information] API.Services.TaskScheduler Enqueuing library scan for: 1
[Kavita] [2024-07-19 17:49:51.531 -04:00  80] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/library/scan?libraryId=1&force=false responded 200 in 98.0060 ms
[Kavita] [2024-07-19 17:49:51.556 -04:00  53] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Comics
[Kavita] [2024-07-19 17:49:51.572 -04:00  53] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library Comics Step 1: Scan Files
[Kavita] [2024-07-19 17:49:51.783 -04:00  53] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library Comics Step 1.A: Process 1 folders
[Kavita] [2024-07-19 17:49:51.783 -04:00  53] [Debug] API.Services.Tasks.ScannerService     [ScannerService] Library Comics Step 1.B: Scan files in /comics
[Kavita] [2024-07-19 17:49:52.632 -04:00  53] [Debug] API.Services.Tasks.ScannerService [ProcessFiles] /comics/Boom Studios is dirty and has multiple series folders, checking if we can avoid a full scan
[Kavita] [2024-07-19 17:50:32.181 -04:00  53] [Debug] API.Services.Tasks.ScannerService     [ScannerService] Library Comics Step 1.C: Process files in /comics
[Kavita] [2024-07-19 18:08:51.561 -04:00  53] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library Comics Step 2: Track Found Series
[Kavita] [2024-07-19 18:08:51.570 -04:00  53] [Debug] API.Services.Tasks.ScannerService [ScannerService] Library Comics Step 3: Process Parsed Series
```

I can't see it in the logs, but it said there was over 6000 changes. I just stopped the container at that point instead of letting it scan for 3 more days. I know this isn't down to how the file system behaves because my manga library in a different container does not do this.

**Comment by Cducharme84** [comment] 2024-09-22 20:45
I did a bit of digging on my library, I've been very focused on adding content that mylar as a management program isn't even aware of so I hadn't been on top of seeing if its efforts are being scanned into existing libraries. I am using ComicVine and current latest hotfix release but just based on age of a few items showing I'm suspecting the issue has gone longer than that.

My environment has 2 types of libraries with regard to structure, for the very large publishers I have a `/Publisher/Series` structure with the Publisher as library root. These are scanning as intended when files are changed or moved and new series/folders are created. So those, and presumably libraries of ComicVine type with that structure (possibly those who used Diesel's script) are all unaffected and their scanners are likely going to be reported as operating as expected.

It is my other libraries which are `/ComicRoot/Publisher/Series` that appear affected - but it's not every updated file that isn't scanned. The criteria for the items missing appears to be, from observation, that they are created under a previously scanned subfolder of the library root into another subfolder which can have existed previously or not. So newly created publisher folders have their contents scanned that first scan no problem then having been scanned they fall under the no-update criteria.

Things I've tested and results - 
Moved a folder not scanning out of the publisher folder - Result scanned in new location 
After above moving back to publisher folder - Series deleted on series scan as missing from `/root/Series` and not picked up in original location
Force scan on affected library type - Getting a large amount of additions from publishers with contents able to be verified in file system and mylar as placed weeks ago.

Temporary remedy - 
For affected libraries a force scan periodically is a resource expensive but surefire way to catch these.

Hypothesis on cause -
I suspect it will be found within the folder dirty logic but I'm definitely not proficient in the language to help truly do more than offer conjecture.

**Comment by majora2007** [comment] 2024-09-22 20:53
@Cducharme84 You are 100%, the dirty folder logic, which is an optimization I added, is what is causing these folder scan issues. The idea behind this was that previously, when checking for dirty folders, due to `root/publisher/series` layout, if one series in the publisher was dirty, the whole publisher folder would be processed. 

I wanted to reduce the scan and instead find the underlying series folders that were dirty and enqueue those up for scans instead of the whole Publisher folder. However, there must be a logic issue that is causing it to not properly function. If anyone does know how to code, I am extremely open to help on this.

**Comment by majora2007** [comment] 2024-10-24 15:27
Fixed with the new scanner. Validated by Morsok.

**Closed as completed by majora2007** 2024-10-24 15:27 UTC
Labels: bug, Scanner

**Comment by Cducharme84** [comment] 2024-10-25 14:26
Can definitely attest that the new scanner not only resolves this bit but makes an entire `/root/` library now possible to scan into even when over 900 folders from root and 67k files. Hopefully folks will appreciate the monumental lift that rework was!
