### ISSUE TITLE
Disappearing volume covers

### ISSUE THREAD

**Issue by coscosname** [Kareadita/Kavita#1281] opened 2022-05-24 19:16 UTC
I have the same problem with the volume covers as #1249. (Kavita Version 0.5.3.0)

From what I've noticed the problem is due to the fact that the volume cover is set for some (random?) chapter of a volume and not for the volume itself.

When fetching the volume covers in the volume list, they are fetched as `volume-cover`.
`Request starting HTTP/1.1 GET http://mysite.abc/api/image/volume-cover?volumeId=166&offset=0 - -`.
 which gives us the volume cover.

![image](https://user-images.githubusercontent.com/89737988/170107748-cc1baefe-deb9-4318-b382-371c1aaf6701.png)

And when editing a volume and the cover shown there comes from some chapter of the given volume (random?) `chapter-cover`.
`Request starting HTTP/1.1 GET http://mysite.abc/api/image/chapter-cover?chapterId=531 - -`

![image](https://user-images.githubusercontent.com/89737988/170108186-c5af2f54-e17d-47e7-b8df-c8e2df4250eb.png)

Chapter with "volume cover"
![image](https://user-images.githubusercontent.com/89737988/170109485-bd96e451-5ce9-42a8-bf4b-cd18ed20e035.png)

When we check the chapter ID, we find that it is the same as the "cover" in the volume metadata edition (chapterId=531).
![image](https://user-images.githubusercontent.com/89737988/170109771-dc631a8d-1914-4265-b39f-945262617f07.png)

The implication is that when adding a volume cover, it is assigned as the cover of some (random?) chapter from that volume and not to the volume itself. So when displaying volumes we get the "original" covers because they are taken from `volume-cover` and when editing the volume metadata we get the preset cover because there it is taken from some chapter `chapter-cover`

It follows that the problem is:
- assigning the cover to the volume
- getting the cover in the metadata edition

_Originally posted by @coscosname in https://github.com/Kareadita/Kavita/issues/1249#issuecomment-1136316540_

**Comment by coscosname** [comment] 2022-05-27 01:08
The set volume covers are correct until the browser cache is cleared. (The covers in the metadata edit do not disappear.)

To me, the problem seems to be that such a query `http://mysite.abc/api/image/volume-cover?volumeId=166&offset=0` That always returns the original volume cover, even after setting a new one. This is used in the volume list.

When editing the volume metadata we have `http://mysite.abc/api/image/chapter-cover?chapterId=531` That is, the chapter to which the new volume cover has been assigned. So it displays what has been set.

The current behavior seems strange to me because if I set covers for all chapters and then a cover for a volume then one of the chapter covers will be replaced by the volume cover which is rather unwanted behavior.

**Comment by majora2007** [comment] 2022-09-12 14:27
The reason why a chapter image gets overridden with the Volume is because they are linked. It's how the system was designed. I'm going to leave this open as a potential enhancement to decouple them. I'll do the investigation and close the issue if it's a no go, else a PR will be linked against the issue.

**Closed** 2023-05-10 18:05 UTC
Labels: enhancement, UI
