### ISSUE TITLE
0.5.2 Loses Reading Percentage / Bookmark

### ISSUE THREAD

**Issue by dathbe** [Kareadita/Kavita#1194] opened 2022-04-04 00:11 UTC
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Upgrading to 0.5.2 loses information on read progress of books.

Only some information is lost.  If you look at the thumbnail of the book, there is still a green bar indicating it is being read.  But the books do not appear on the home page, and opening the book seems to mostly take you back to the beginning of the book (it did for me in 3 out of the 5 books that I was reading).

**To Reproduce**
1) upgrade from 0.5.1 to 0.5.2
2) go to home page
3) notice that the books you are reading no longer appear in the "On Deck" section

**Expected behavior**
Read progress will be saved on upgrade

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version 98.0.2

**Smartphone (please complete the following information):**
 - Device: n/a

**Additional context**
Thanks

**Comment by dathbe** [comment] 2022-04-04 13:51
> This is not enough information to determine the issue. Can you confirm that reading progress is indeed lost? If you're just basing on On Deck from homepage, I am well aware there is a bug on it. I released with the bug in mind so I can take a bigger stab at it in the upcoming release.

It definitely did lose reading progress.

I have a strong suspicion that it retained information on which _chapter_ you were reading, but not _where in the chapter_ you were.  Thus, for the 2/5 books that I said it "didn't lose" my read progress, it is probably because I was at the beginning of a chapter late in the book.  Whereas for the 3 that it "did lose" my read progress, I was somewhere in the middle of the first chapter, and it reverted me back to the top of the chapter.

This is not the biggest of deals, and thankfully I only had 5 books to remember, but if there's a known bug it would be nice if that is listed in the release notes.

I'm happy to give any more information.  Let me know what you need.

**Comment by majora2007** [comment] 2022-04-04 23:21
I'm not sure how to proceed from here. I can't reproduce any issues nor has any user reported anything during testing or post release. My personal server didn't have any issues. Only On Deck was touched, progress hasn't been touched in some time. 

Were these books (epub) perhaps? Maybe the book reader code where we added a slight timeout for apple devices so the scroll could scroll down is causing an issue? Are you using Firefox on an Apple product?

**Comment by dathbe** [comment] 2022-04-04 23:55
Maybe I had a quirk in my system.  It was 100% an epub issue, and scroll sounds like a likely culprit given that the chapter progress was kept, but scroll progress within the chapter was lost.  (I hope I'm using the word "chapter" right here.  I mean the segments you have to click right or left to change between in epub.)  I noticed the problem on Firefox on Windows.  Did not check with other combinations.

**Comment by dathbe** [comment] 2022-04-04 23:56
I should add that I use Kavita exclusively for my epub.  It's the best self-hosted e-reader I've found.  I keep my comix collection in another system (shame on me) that can't handle epub.

**Comment by majora2007** [comment] 2022-04-05 20:16
To each their own. Because I can't reproduce this and it seems you've already fixed the progress by re-scrolling, I'm going to close this. If you see it happen again, feel free to post on here with more data and we can try to solve it.

**Closed by majora2007** 2022-04-05 20:16 UTC
Labels: information-needed, can't reproduce

**Comment by dathbe** [comment] 2022-05-04 20:19
I now think this issue may have been more about my "On Deck" section emptying than actually losing my read percentage on any books.  I treat "On Deck" as books that I'm in the middle of reading, but maybe it's books that I have read _recently_?  I don't know how "On Deck" is calculated.  But it would be nice to have the books I'm in the middle of reading displayed on the Home page, even if I haven't picked them up in a year.

**Comment by majora2007** [comment] 2022-05-04 20:39
On Deck is supposed to be series with active reading progress on them in the last month. 

But after testing the new On Deck in nightly, which functions more to the goal with regards to sorting based on last chapter added then reading order, I'm opting to split On Deck into 2 streams: In Progress and Recently Updated (name pending). So I think this will be more inline with what you are looking for.

**Comment by dathbe** [comment] 2022-05-04 20:45
Sounds like exactly what I am envisioning.  Thanks!
