### ISSUE TITLE
Problem with epub Metadata "No metadata avalible"

### ISSUE THREAD

**Issue by Rougecarlos** [Kareadita/Kavita#1361] opened 2022-07-03 22:59 UTC
Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

Windows 10
Kavita: Version 0.5.4.0

With some Epubs, after going through Calibre and putting in the metadata, it can't find them.
This text appears:
"No metadata available"
I attach an Epub with which it happens to me, if you can't, sorry and have some admin delete it

https://mega.nz/file/ZHlFzAgQ#1Wncjvh7MetbBkdG8LI_ZLkxsNDLkZtF7E8UTh8dqO8

I have tried with this program to save the metadata also just in case, but the result is the same

https://github.com/benchen71/epub-metadata-editor

**Comment by Sp4rky001** [comment] 2022-07-05 14:42
Have you tried right-clicking on the books and selecting polish books?  I had to do this for all of my books to ensure that they identified with the correct series

**Comment by therobbiedavis** [comment] 2022-07-05 14:54
> Please put as much information as possible to help me understand your issue. OS, browser, version are very important!
> 
> Windows 10 Kavita: Version 0.5.4.0
> 
> With some Epubs, after going through Calibre and putting in the metadata, it can't find them. This text appears: "No metadata available" I attach an Epub with which it happens to me, if you can't, sorry and have some admin delete it
> 
> https://mega.nz/file/ZHlFzAgQ#1Wncjvh7MetbBkdG8LI_ZLkxsNDLkZtF7E8UTh8dqO8
> 
> I have tried with this program to save the metadata also just in case, but the result is the same
> 
> https://github.com/benchen71/epub-metadata-editor

I'm sorry, I don't understand the issue here. Is this issue with Calibre or Kavita? If Kavita, can you clarify the issue a bit more?

**Comment by Rougecarlos** [comment] 2022-07-07 20:03
I has download both files por windows kavita x86 & x64, with the new instalation in both, the epub that was "86 - EIGHTY-SIX, Vol.01.epub" dont show any metadata, i was delete and scan a few times but always with no metada.
Tomorrow try i go to check it in Linux, i don't know why you can see it, and i don't

**Comment by Rougecarlos** [comment] 2022-07-08 00:02
I tried on windows and it does not show the metadata, on linux (Manjaro XFCE) and neither, but I have been putting docker and it does take it.
I don't know why the epubs are always the same.
For now I will settle for docker, but if you want to look at it I think something is wrong with the other versions.

**Comment by therobbiedavis** [comment] 2022-07-08 02:00
I just downloaded the 0.5.4.0 windows 64 build and created a new instance. It still seems to be picking up the metadata...

![image](https://user-images.githubusercontent.com/7907265/177901392-bbfd41cf-d6cc-4f34-9d10-269666d8da72.png)

**Comment by Rougecarlos** [comment] 2022-07-08 08:44
Well, I don't know, you catch me there, in windows with a new installation it doesn't recognize the metadata of that file.
I will have a conflict with something else I think. If someone else could test it, that would be great.
Anyway, thanks for helping me out.

**Comment by majora2007** [comment] 2022-07-10 13:04
I'll take a look into this in a few once I'm back from holiday.

**Comment by majora2007** [comment] 2022-07-13 17:13
I was also unable to reproduce. Downloaded file, did a library scan and all metadata available. Would you be able to ensure you're on Debug logging level, clear your logs, do the scan of just this one book (create a test library just with this one book) then send me the log files?

**Comment by Rougecarlos** [comment] 2022-07-18 04:46
I dont know how to "Would you be able to ensure you're on Debug logging level, clear your logs"
I was download Win 64 exe, start Kavita, make user and password and add the ebook of the frist post and it not show metadata.
Then i go to settings, Task, Download logs, is this that you need? or something else?
This is the file created https://mega.nz/file/xK1SRRpZ#cyqcHyUFOqk4YYX6ELVX2MTPb6oTfAEZt-1tLDUZaYQ

**Comment by Rougecarlos** [comment] 2022-07-18 05:04
I was make a video of the new instalation of the kavita, for ir you want see it, is only about 2 min
https://youtu.be/g5-_vavHhgc
And this is the file i was download with the option of the logs in this video
https://mega.nz/file/xK1SRRpZ#cyqcHyUFOqk4YYX6ELVX2MTPb6oTfAEZt-1tLDUZaYQ

I dont know why this happens to me, but with the docker version all the metadata loads well :S

**Comment by Rougecarlos** [comment] 2022-07-29 04:08
@majora2007 Is this log that you need or something else?

**Comment by majora2007** [comment] 2022-08-09 12:14
Closing this as you've created a new issue (which you could have just updated here with new findings)

**Closed by majora2007** 2022-08-09 12:14 UTC
Labels: can't reproduce
